<center>
    <h1><strong>GROUP 11</strong></h1>
    <h2>The Linear Regression Model</h2>
</center>

<h3>Group Members</h3>
Onte, Michael Jethro M.<br>
Sunga, Jullianne Christille N.<br>
Villegas, Renz Justine L.<br>

<h1>Importing Required Libraries</h1>
This file contains all the libraries that are required for the project.

In [505]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, KFold, cross_val_score, GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, explained_variance_score, r2_score
# import linear regression model
from sklearn.linear_model import LinearRegression

# for showing the proper table
from IPython.display import display

<h1>Loading and Viewing Data for Cross Validation in 10 folds</h1>
Import the database for all the features.

In [506]:
# read the data
(df_norm := pd.read_csv('Group 11_CompleteDataset.csv'))

,Dedicated Graphic Memory Capacity,SSD Capacity,RAM,Clock Speed,Cache,Number of Cores,Screen Size,Screen Resolution,Wireless LAN,Bluetooth,...,Brand_dell,Brand_hp,Brand_infinix,Brand_lenovo,Brand_mi,Brand_msi,Brand_nokia,Brand_redmibook,Brand_vaio,Price
0,0.50,0.50,1.000,0.961538,1.000000,1.000000,1.000000,0.400000,1.000000,0.866667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.778138
1,0.50,0.50,1.000,0.961538,1.000000,1.000000,0.901684,0.400000,1.000000,0.866667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.761581
2,0.25,0.25,0.500,0.846154,0.666667,0.571429,0.930587,0.225000,1.000000,0.866667,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.344684
3,0.25,0.25,0.500,0.615385,0.666667,0.571429,0.901684,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.290463
4,0.00,0.25,0.500,0.461538,0.333333,0.285714,0.809285,0.225000,1.000000,0.833333,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.259595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,0.00,0.25,0.500,0.942308,0.333333,0.285714,0.809285,0.400000,0.833333,0.850000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.711149
647,0.00,0.25,0.250,0.807692,0.250000,0.285714,0.809285,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.178781
648,0.00,0.25,0.500,0.865385,0.333333,0.285714,0.768776,0.225000,1.000000,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.793930
649,0.00,0.25,0.250,0.769231,0.125000,0.428571,0.768776,0.225000,0.833333,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.283304
650,0.00,0.00,0.125,0.692308,0.041667,0.142857,0.809285,0.113833,0.833333,0.683333,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.147654

<h2>Independent and Dependent Variables.</h2>
Creates a matrix of independent variables and a matrix of dependent variables.

In [507]:

# create a matrix of dependent variables
X_norm = df_norm.drop(['Price'], axis=1).values

print("Normal Independent Variable Array:")
display(pd.DataFrame(X_norm))

# create a matrix of independent variables
Y_norm = df_norm['Price'].values

print("Normal Dependent Variable Array:")
display(pd.DataFrame(Y_norm))

Normal Independent Variable Array:

,0,1,2,3,4,5,6,7,8,9,...,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040
0,0.50,0.50,1.000,0.961538,1.000000,1.000000,1.000000,0.400000,1.000000,0.866667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.50,0.50,1.000,0.961538,1.000000,1.000000,0.901684,0.400000,1.000000,0.866667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.25,0.25,0.500,0.846154,0.666667,0.571429,0.930587,0.225000,1.000000,0.866667,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.25,0.25,0.500,0.615385,0.666667,0.571429,0.901684,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.25,0.500,0.461538,0.333333,0.285714,0.809285,0.225000,1.000000,0.833333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,0.00,0.25,0.500,0.942308,0.333333,0.285714,0.809285,0.400000,0.833333,0.850000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
647,0.00,0.25,0.250,0.807692,0.250000,0.285714,0.809285,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
648,0.00,0.25,0.500,0.865385,0.333333,0.285714,0.768776,0.225000,1.000000,0.833333,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
649,0.00,0.25,0.250,0.769231,0.125000,0.428571,0.768776,0.225000,0.833333,0.833333,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
650,0.00,0.00,0.125,0.692308,0.041667,0.142857,0.809285,0.113833,0.833333,0.683333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

Normal Dependent Variable Array:

            0
0    0.778138
1    0.761581
2    0.344684
3    0.290463
4    0.259595
..        ...
646  0.711149
647  0.178781
648  0.793930
649  0.283304
650  0.147654

[651 rows x 1 columns]

<h2>Training and Testing Datasets</h2>
Split the data into training and testing datasets

In [508]:
X_norm_train, X_norm_test, Y_norm_train, Y_norm_test = train_test_split(X_norm, Y_norm, test_size=0.2, random_state=0)

print("Normal X Train:")
display(pd.DataFrame(X_norm_train))

print("Normal X Test:")
display(pd.DataFrame(X_norm_test))

print("Normal Y Train:")
display(pd.DataFrame(Y_norm_train))

print("Normal Y Test:")
display(pd.DataFrame(Y_norm_test))

Normal X Train:

,0,1,2,3,4,5,6,7,8,9,...,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040
0,0.00,0.125,0.250,0.788462,0.250000,0.142857,0.864816,0.225000,0.833333,0.683333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.25,0.125,0.500,0.961538,0.666667,0.571429,0.901684,0.225000,1.000000,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.00,0.250,0.500,0.807692,0.333333,0.285714,0.809285,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.00,0.000,0.250,0.692308,0.250000,0.285714,0.901684,0.225000,0.833333,0.683333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.125,0.250,0.673077,0.208333,0.142857,0.901684,0.225000,0.833333,0.700000,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,0.00,0.250,0.500,0.807692,0.333333,0.571429,0.774693,0.225000,1.000000,0.850000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
516,0.00,0.000,0.250,0.692308,0.250000,0.285714,0.901684,0.225000,0.833333,0.683333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
517,0.00,0.250,0.500,0.865385,0.333333,0.285714,0.809285,0.225000,1.000000,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
518,0.00,0.250,0.250,0.711538,0.250000,0.285714,0.901684,0.225000,0.833333,0.700000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
519,0.00,0.000,0.125,0.653846,0.166667,0.142857,0.901684,0.113833,0.833333,0.683333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Normal X Test:

,0,1,2,3,4,5,6,7,8,9,...,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040
0,0.000,0.250,0.250,0.807692,0.333333,0.285714,0.809285,0.225000,1.000000,0.850000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.250,0.250,0.500,0.884615,1.000000,0.571429,0.901684,0.225000,1.000000,0.850000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.000,0.250,0.500,0.750000,0.333333,0.285714,0.809285,0.225000,1.000000,0.850000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000,0.250,0.250,0.711538,0.250000,0.285714,0.901684,0.225000,0.833333,0.700000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.125,0.250,0.500,0.807692,0.333333,0.285714,0.809285,0.444444,0.833333,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,0.000,0.125,0.125,0.596154,0.166667,0.285714,0.901684,0.225000,0.833333,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
127,0.125,0.250,0.250,0.807692,0.250000,0.285714,0.809285,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
128,0.000,0.000,0.125,0.692308,0.041667,0.142857,0.809285,0.113833,0.833333,0.683333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
129,0.000,0.125,0.250,0.673077,0.166667,0.142857,0.864816,0.225000,0.833333,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
130,0.000,0.125,0.250,0.788462,0.250000,0.142857,0.901684,0.225000,1.000000,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Normal Y Train:

            0
0    0.129110
1    0.228451
2    0.165535
3    0.148978
4    0.137389
..        ...
515  0.495530
516  0.148978
517  0.235074
518  0.168847
519  0.112553

[520 rows x 1 columns]

Normal Y Test:

            0
0    0.188715
1    0.390708
2    0.168847
3    0.164211
4    0.294679
..        ...
126  0.119209
127  0.182122
128  0.147654
129  0.115865
130  0.168847

[131 rows x 1 columns]

<h1>Linear Regression Model</h1>
Create a linear regression model then fit the training datasets

In [509]:
# create a linear regression model
norm_linear_regression = LinearRegression()
norm_linear_regression.fit(X_norm_train, Y_norm_train)

# predict the test set results
Y_norm_pred = norm_linear_regression.predict(X_norm_test)

# show the comparison between the actual and predicted values
pd.DataFrame({'Actual': Y_norm_test, 'Predicted': Y_norm_pred}).head(20).applymap('{:f}'.format)

      Actual             Predicted
0   0.188715  1318999594353.267334
1   0.390708   -14380367207.437622
2   0.168847              0.166565
3   0.164211   -28114984004.815002
4   0.294679    55914597161.118164
5   0.196993  -227445117057.630371
6   0.198649   133344296482.331604
7   0.123812              0.147339
8   0.092685  -172800975169.429199
9   0.540382              0.550537
10  0.196993    54323131173.022827
11  0.304613   -82335022507.511169
12  0.112583  -125536983853.548584
13  0.220173              0.237488
14  0.288056  -233079895286.833313
15  0.185404   201246084528.553162
16  1.000000   -64607197715.198914
17  0.208583   158965548658.508179
18  0.284745   187263314924.846130
19  0.211894              0.271973

<h2>K-Fold Cross Validation</h2>
Use k-fold cross validation to get the accuracy of the model

In [510]:
norm_kfold = KFold(n_splits=10, random_state=0, shuffle=True)

<h3>Mean Absolute Error</h3>
Using mean absolute error of the model as scoring for cross validation

In [511]:
# calculate the mean absolute error of the model as scoring for cross validation
norm_MAE = -cross_val_score(norm_linear_regression, X_norm, Y_norm, cv=norm_kfold, scoring='neg_mean_absolute_error')


print( f"Normal Mean Absolute Error of k-Folds: \033[1m\033[94m{(norm_MAE)}\033[0m")
print( f"Average Normal Mean Absolute Error of k-Folds: \033[1m\033[94m{(norm_MAE.mean())}\033[0m")
print( f"Standard Deviation of Normal Mean Absolute Error of k-Folds: \033[1m\033[94m{(norm_MAE.std())}\033[0m")

Normal Mean Absolute Error of k-Folds: [143600110377.258667 125615039052.744324 153866459418.061737
 209553478008.829987 187980501852.959442 325773399038.670959
 287562216955.273926 164818122582.962219 232418260128.600494
 148315438933.416382]
Average Normal Mean Absolute Error of k-Folds: 197950302634.87784
Standard Deviation of Normal Mean Absolute Error of k-Folds: 62834854898.340645

<h3>Mean Squared Error</h3>
Using mean squared error of the model as scoring for cross validation

In [512]:
norm_MSE = -cross_val_score(norm_linear_regression, X_norm, Y_norm, cv=norm_kfold, scoring='neg_mean_squared_error')

print( f"Normal Mean Squared Error of k-Folds: \033[1m\033[94m{(norm_MSE)}\033[0m")
print( f"Average Normal Mean Squared Error of k-Folds: \033[1m\033[94m{(norm_MSE.mean())}\033[0m")
print( f"Standard Deviation of Normal Mean Squared Error of k-Folds: \033[1m\033[94m{(norm_MSE.std())}\033[0m")

Normal Mean Squared Error of k-Folds: [67096437207620955144192.000000 76759630551688574664704.000000
 93682647203170622636032.000000 146559782338563800039424.000000
 107701077460563093618688.000000 347848404507180484526080.000000
 232723582930352433266688.000000 71458433268312537300992.000000
 166699456843255098900480.000000 61788200694937460670464.000000]
Average Normal Mean Squared Error of k-Folds: 1.3723176530056451e+23
Standard Deviation of Normal Mean Squared Error of k-Folds: 8.706072930881672e+22

<h3>R-Squared</h3>
Using r-squared of the model as scoring for cross validation

In [513]:
norm_R2 = -cross_val_score(norm_linear_regression, X_norm, Y_norm, cv=norm_kfold, scoring='r2')

print( f"Normal R2 of k-Folds: \033[1m\033[94m{(norm_R2)}\033[0m")
print( f"Average Normal R2 of k-Folds: \033[1m\033[94m{(norm_R2.mean())}\033[0m")
print( f"Standard Deviation of Normal R2 of k-Folds: \033[1m\033[94m{(norm_R2.std())}\033[0m")

Normal R2 of k-Folds: [2042801739825061856018432.000000 3244241082313853926113280.000000
 7166970394043035083079680.000000 11389757564542399807488000.000000
 9614378545779489034469376.000000 16965202534465346618785792.000000
 20688206163978962652364800.000000 5216813208282136571805696.000000
 12429973625282281930227712.000000 6645599186173183511232512.000000]
Average Normal R2 of k-Folds: 9.540394404468576e+24
Standard Deviation of Normal R2 of k-Folds: 5.654542831098282e+24

<h3>Explained Variance Score</h3>
Using explained variance score of the model as scoring for cross validation

In [514]:
norm_EV = -cross_val_score(norm_linear_regression, X_norm, Y_norm, cv=norm_kfold, scoring='explained_variance')

print( f"Normal Explained Variance of k-Folds: \033[1m\033[94m{(norm_EV)}\033[0m")
print( f"Average Normal Explained Variance of k-Folds: \033[1m\033[94m{(norm_EV.mean())}\033[0m")
print( f"Standard Deviation of Normal Explained Variance of k-Folds: \033[1m\033[94m{(norm_EV.std())}\033[0m")

Normal Explained Variance of k-Folds: [2007969360929775710896128.000000 3241227734852809940533248.000000
 6462426909441397346009088.000000 11383195563587384591253504.000000
 9589297145169779410075648.000000 16766788582362701166018560.000000
 20410760580226764024840192.000000 5212677880254763110498304.000000
 12420391667573847268261888.000000 6133851834214627313451008.000000]
Average Normal Explained Variance of k-Folds: 9.362858725861383e+24
Standard Deviation of Normal Explained Variance of k-Folds: 5.639039018562067e+24

<h3>Root Mean Squared Error</h3>
Using root mean squared error of the model as scoring for cross validation

In [515]:
norm_RMSE = np.sqrt(norm_MSE)

print( f"Normal Root Mean Squared Error: \033[1m\033[94m{(norm_RMSE)}\033[0m")
print( f"Average Normal Root Mean Squared Error: \033[1m\033[94m{(norm_RMSE.mean())}\033[0m")
print( f"Standard Deviation of Normal Root Mean Squared Error: \033[1m\033[94m{(norm_RMSE.std())}\033[0m")

Normal Root Mean Squared Error: [259029799844.768738 277055284287.610352 306076211429.719910
 382831271369.729919 328178423209.940918 589786744940.220337
 482414327036.783203 267317102461.313782 408288448089.405396
 248572324877.363342]
Average Normal Root Mean Squared Error: 354954993754.68555
Standard Deviation of Normal Root Mean Squared Error: 106012818607.82506

<h2>Hold-Out Validation</h2>
Use hold-out validation to evaluate the model

<h3>Mean Absolute Error</h3>
Using mean absolute error of the model as scoring for hold-out validation <i>(the best value is 0.0)</i>

In [516]:
norm_MAE_holdout = mean_absolute_error(Y_norm_test, Y_norm_pred)
color = "\033[92m" if norm_MAE_holdout < 0.5 else "\033[91m"

print( f"Normal Mean Absolute Error of Holdout: \033[1m{color}{norm_MAE_holdout}\033[0m")

Normal Mean Absolute Error of Holdout: 162286526976.644

<h3>Mean Squared Error</h3>
Using mean squared error of the model as scoring for hold-out validation <i>(the best value is 0.0)</i>

In [517]:
norm_MSE_holdout = mean_squared_error(Y_norm_test, Y_norm_pred)
color = "\033[92m" if norm_MSE_holdout < 0.5 else "\033[91m"

print( f"Normal Mean Squared Error of Holdout: \033[1m{color}{norm_MSE_holdout}\033[0m")

Normal Mean Squared Error of Holdout: 2.1314681880906375e+23

<h3>R-Squared Error</h3>
Using r-squared error of the model as scoring for hold-out validation <i>(the best value is 1.0)</i>

In [518]:
norm_R2_holdout = r2_score(Y_norm_test, Y_norm_pred)
color = "\033[92m" if norm_R2_holdout > 0.5 else "\033[91m"

print( f"Normal R2 of Holdout: \033[1m{color}{norm_R2_holdout}\033[0m")

Normal R2 of Holdout: -7.519279853384749e+24

<h3>Explained Variance Score</h3>
Using explained variance score of the model as scoring for hold-out validation  <i>(the best value is 1.0)</i>

In [519]:
norm_EV_holdout = explained_variance_score(Y_norm_test, Y_norm_pred)
color = "\033[92m" if norm_EV_holdout > 0.5 else "\033[91m"

print( f"Normal Explained Variance of Holdout: \033[1m{color}{norm_EV_holdout}\033[0m")

Normal Explained Variance of Holdout: -7.444000974712178e+24

<h3>Root Mean Squared Error</h3>
Using root mean squared error of the model as scoring for hold-out validation  <i>(the best value is 0.0)</i>

In [520]:
norm_RMSE_holdout = np.sqrt(norm_MSE_holdout)
color = "\033[92m" if norm_RMSE_holdout < 0.5 else "\033[91m"

print( f"Normal Root Mean Squared Error of Holdout: \033[1m{color}{norm_RMSE_holdout}\033[0m")

Normal Root Mean Squared Error of Holdout: 461678263305.8045

<h1>Loading and Viewing Data for Cross Validation in 10 folds</h1>
Import the database with the features selected.

In [521]:
# read the data
(df_sel := pd.read_csv('Group 11_Dataset.csv'))

,Dedicated Graphic Memory Capacity,SSD Capacity,RAM,Cache,Screen Resolution,Bluetooth,Weight,Brightness,Refresh Rate,HDD Capacity,...,Warranty Summary_3 Year Carry-In Warranty,Warranty Summary_3 Year Premier Support Warranty,Brand_asus,Brand_dell,Brand_hp,Brand_infinix,Brand_lenovo,Brand_msi,Brand_redmibook,Price
0,0.50,0.50,1.000,1.000000,0.400000,0.866667,1.000000,0.500000,0.166667,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.778138
1,0.50,0.50,1.000,1.000000,0.400000,0.866667,0.793103,0.500000,0.166667,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.761581
2,0.25,0.25,0.500,0.666667,0.225000,0.866667,0.855172,0.500000,0.400000,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.344684
3,0.25,0.25,0.500,0.666667,0.225000,0.833333,0.775862,0.416667,0.333333,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.290463
4,0.00,0.25,0.500,0.333333,0.225000,0.833333,0.468966,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.259595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,0.00,0.25,0.500,0.333333,0.400000,0.850000,0.375862,0.500000,0.166667,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.711149
647,0.00,0.25,0.250,0.250000,0.225000,0.833333,0.379310,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.178781
648,0.00,0.25,0.500,0.333333,0.225000,0.833333,0.513793,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.793930
649,0.00,0.25,0.250,0.125000,0.225000,0.833333,0.455172,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.283304
650,0.00,0.00,0.125,0.041667,0.113833,0.683333,0.551724,0.416667,0.166667,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.147654

<h2>Independent and Dependent Variables.</h2>
Creates a matrix of independent variables and a matrix of dependent variables.

In [522]:

# create a matrix of dependent variables
X_sel = df_sel.drop(['Price'], axis=1).values

print("selal Independent Variable Array:")
display(pd.DataFrame(X_sel))

# create a matrix of independent variables
Y_sel = df_sel['Price'].values

print("selal Dependent Variable Array:")
display(pd.DataFrame(Y_sel))

selal Independent Variable Array:

,0,1,2,3,4,5,6,7,8,9,...,275,276,277,278,279,280,281,282,283,284
0,0.50,0.50,1.000,1.000000,0.400000,0.866667,1.000000,0.500000,0.166667,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.50,0.50,1.000,1.000000,0.400000,0.866667,0.793103,0.500000,0.166667,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.25,0.25,0.500,0.666667,0.225000,0.866667,0.855172,0.500000,0.400000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.25,0.25,0.500,0.666667,0.225000,0.833333,0.775862,0.416667,0.333333,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.00,0.25,0.500,0.333333,0.225000,0.833333,0.468966,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,0.00,0.25,0.500,0.333333,0.400000,0.850000,0.375862,0.500000,0.166667,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
647,0.00,0.25,0.250,0.250000,0.225000,0.833333,0.379310,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
648,0.00,0.25,0.500,0.333333,0.225000,0.833333,0.513793,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
649,0.00,0.25,0.250,0.125000,0.225000,0.833333,0.455172,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
650,0.00,0.00,0.125,0.041667,0.113833,0.683333,0.551724,0.416667,0.166667,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

selal Dependent Variable Array:

            0
0    0.778138
1    0.761581
2    0.344684
3    0.290463
4    0.259595
..        ...
646  0.711149
647  0.178781
648  0.793930
649  0.283304
650  0.147654

[651 rows x 1 columns]

<h2>Training and Testing Datasets</h2>
Split the data into training and testing datasets

In [523]:
X_sel_train, X_sel_test, Y_sel_train, Y_sel_test = train_test_split(X_sel, Y_sel, test_size=0.2, random_state=0)

print("Selected Features X Train:")
display(pd.DataFrame(X_sel_train))

print("Selected Features X Test:")
display(pd.DataFrame(X_sel_test))

print("Selected Features Y Train:")
display(pd.DataFrame(Y_sel_train))

print("Selected Features Y Test:")
display(pd.DataFrame(Y_sel_test))

Selected Features X Train:

,0,1,2,3,4,5,6,7,8,9,...,275,276,277,278,279,280,281,282,283,284
0,0.00,0.125,0.250,0.250000,0.225000,0.683333,0.544828,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.25,0.125,0.500,0.666667,0.225000,0.833333,0.737931,0.416667,0.333333,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.00,0.250,0.500,0.333333,0.225000,0.833333,0.482759,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.00,0.000,0.250,0.250000,0.225000,0.683333,0.620690,0.333333,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.125,0.250,0.208333,0.225000,0.700000,0.627586,0.416667,0.166667,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,0.00,0.250,0.500,0.333333,0.225000,0.850000,0.400000,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
516,0.00,0.000,0.250,0.250000,0.225000,0.683333,0.620690,0.416667,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
517,0.00,0.250,0.500,0.333333,0.225000,0.833333,0.503448,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
518,0.00,0.250,0.250,0.250000,0.225000,0.700000,0.610345,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
519,0.00,0.000,0.125,0.166667,0.113833,0.683333,0.620690,0.333333,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

Selected Features X Test:

,0,1,2,3,4,5,6,7,8,9,...,275,276,277,278,279,280,281,282,283,284
0,0.000,0.250,0.250,0.333333,0.225000,0.850000,0.479310,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.250,0.250,0.500,1.000000,0.225000,0.850000,0.827586,0.416667,0.333333,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.000,0.250,0.500,0.333333,0.225000,0.850000,0.510345,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.000,0.250,0.250,0.250000,0.225000,0.700000,0.610345,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.125,0.250,0.500,0.333333,0.444444,0.833333,0.465517,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,0.000,0.125,0.125,0.166667,0.225000,0.833333,0.620690,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
127,0.125,0.250,0.250,0.250000,0.225000,0.833333,0.465517,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
128,0.000,0.000,0.125,0.041667,0.113833,0.683333,0.551724,0.416667,0.166667,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
129,0.000,0.125,0.250,0.166667,0.225000,0.833333,0.620690,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
130,0.000,0.125,0.250,0.250000,0.225000,0.833333,0.620690,1.000000,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

Selected Features Y Train:

            0
0    0.129110
1    0.228451
2    0.165535
3    0.148978
4    0.137389
..        ...
515  0.495530
516  0.148978
517  0.235074
518  0.168847
519  0.112553

[520 rows x 1 columns]

Selected Features Y Test:

            0
0    0.188715
1    0.390708
2    0.168847
3    0.164211
4    0.294679
..        ...
126  0.119209
127  0.182122
128  0.147654
129  0.115865
130  0.168847

[131 rows x 1 columns]

<h1>Linear Regression Model</h1>
Create a linear regression model then fit the training datasets

In [524]:
# create a linear regression model
sel_linear_regression = LinearRegression()
sel_linear_regression.fit(X_sel_train, Y_sel_train)

# predict the test set results
Y_sel_pred = sel_linear_regression.predict(X_sel_test)

# show the comparison between the actual and predicted values
pd.DataFrame({'Actual': Y_sel_test, 'Predicted': Y_sel_pred}).head(20).applymap('{:f}'.format)

      Actual          Predicted
0   0.188715           0.204530
1   0.390708           0.385969
2   0.168847           0.186794
3   0.164211           0.173617
4   0.294679           0.235147
5   0.196993           0.186116
6   0.198649           0.202450
7   0.123812           0.132051
8   0.092685           0.123007
9   0.540382           0.540386
10  0.196993           0.179682
11  0.304613           0.285061
12  0.112583           0.106699
13  0.220173           0.197580
14  0.288056           0.268651
15  0.185404           0.199761
16  1.000000  2789942374.081335
17  0.208583           0.188191
18  0.284745           0.271928
19  0.211894           0.219971

<h2>K-Fold Cross Validation</h2>
Use k-fold cross validation to get the accuracy of the model

In [525]:
sel_kfold = KFold(n_splits=10, random_state=0, shuffle=True)

<h3>Mean Absolute Error</h3>
Using mean absolute error of the model as scoring for cross validation

In [526]:
# calculate the mean absolute error of the model as scoring for cross validation
sel_MAE = -cross_val_score(sel_linear_regression, X_sel, Y_sel, cv=sel_kfold, scoring='neg_mean_absolute_error')


print( f"Selected Feastures Mean Absolute Error of k-Folds: \033[1m\033[94m{(sel_MAE)}\033[0m")
print( f"Average Selected Feastures Mean Absolute Error of k-Folds: \033[1m\033[94m{(sel_MAE.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures Mean Absolute Error of k-Folds: \033[1m\033[94m{(sel_MAE.std())}\033[0m")

Selected Feastures Mean Absolute Error of k-Folds: [6395170546.857873 956005797.019124 156039437.119603 2090679991.166762
 200842084.548891 410424900.547240 897992030.902982 461899176.984348
 453047734.165312 390558397.219084]
Average Selected Feastures Mean Absolute Error of k-Folds: 1241266009.653122
Standard Deviation of Selected Feastures Mean Absolute Error of k-Folds: 1799620689.528277

<h3>Mean Squared Error</h3>
Using mean squared error of the model as scoring for cross validation

In [527]:
sel_MSE = -cross_val_score(sel_linear_regression, X_sel, Y_sel, cv=sel_kfold, scoring='neg_mean_squared_error')

print( f"Selected Feastures Mean Squared Error of k-Folds: \033[1m\033[94m{(sel_MSE)}\033[0m")
print( f"Average Selected Feastures Mean Squared Error of k-Folds: \033[1m\033[94m{(sel_MSE.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures Mean Squared Error of k-Folds: \033[1m\033[94m{(sel_MSE.std())}\033[0m")

Selected Feastures Mean Squared Error of k-Folds: [896850486640769761280.000000 40000295639903059968.000000
 1288038994484138752.000000 62859026179505561600.000000
 1959474046602786816.000000 10241584289752270848.000000
 14507641835147544576.000000 4347978404657871360.000000
 4074256850214753792.000000 5415161585045445632.000000]
Average Selected Feastures Mean Squared Error of k-Folds: 1.0415439444660832e+20
Standard Deviation of Selected Feastures Mean Squared Error of k-Folds: 2.6491439865536882e+20

<h3>R-Squared</h3>
Using r-squared of the model as scoring for cross validation

In [528]:
sel_R2 = -cross_val_score(sel_linear_regression, X_sel, Y_sel, cv=sel_kfold, scoring='r2')

print( f"Selected Feastures R2 of k-Folds: \033[1m\033[94m{(sel_R2)}\033[0m")
print( f"Average Selected Feastures R2 of k-Folds: \033[1m\033[94m{(sel_R2.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures R2 of k-Folds: \033[1m\033[94m{(sel_R2.std())}\033[0m")

Selected Feastures R2 of k-Folds: [27305290872651960549376.000000 1690610044459346296832.000000
 98538391211562123264.000000 4885030923926303145984.000000
 174920489923305308160.000000 499500786831578103808.000000
 1289671985363515867136.000000 317423572464511614976.000000
 303797661670930251776.000000 582425010241847951360.000000]
Average Selected Feastures R2 of k-Folds: 3.714720973874486e+21
Standard Deviation of Selected Feastures R2 of k-Folds: 7.979939921122252e+21

<h3>Explained Variance Score</h3>
Using explained variance score of the model as scoring for cross validation

In [529]:
sel_EV = -cross_val_score(sel_linear_regression, X_sel, Y_sel, cv=sel_kfold, scoring='explained_variance')

print( f"Selected Feastures Explained Variance of k-Folds: \033[1m\033[94m{(sel_EV)}\033[0m")
print( f"Average Selected Feastures Explained Variance of k-Folds: \033[1m\033[94m{(sel_EV.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures Explained Variance of k-Folds: \033[1m\033[94m{(sel_EV.std())}\033[0m")

Selected Feastures Explained Variance of k-Folds: [26956711980561195859968.000000 1652108882045086728192.000000
 96919584475395932160.000000 4867085960384887128064.000000
 173090505962886332416.000000 491871087354443071488.000000
 1217987184869370494976.000000 315040083985343774720.000000
 293256677169142890496.000000 579840386071672258560.000000]
Average Selected Feastures Explained Variance of k-Folds: 3.664391233287943e+21
Standard Deviation of Selected Feastures Explained Variance of k-Folds: 7.880932225857524e+21

<h3>Root Mean Squared Error</h3>
Using root mean squared error of the model as scoring for cross validation

In [530]:
sel_RMSE = np.sqrt(sel_MSE)

print( f"Selected Feastures Root Mean Squared Error: \033[1m\033[94m{(sel_RMSE)}\033[0m")
print( f"Average Selected Feastures Root Mean Squared Error: \033[1m\033[94m{(sel_RMSE.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures Root Mean Squared Error: \033[1m\033[94m{(sel_RMSE.std())}\033[0m")

Selected Feastures Root Mean Squared Error: [29947462106.842541 6324578692.680095 1134918056.286065 7928368443.728228
 1399812146.897857 3200247535.699742 3808889842.873845 2085180664.752546
 2018478845.619828 2327049974.763208]
Average Selected Feastures Root Mean Squared Error: 6017498631.014395
Standard Deviation of Selected Feastures Root Mean Squared Error: 8242821402.429402

<h2>Hold-Out Validation</h2>
Use hold-out validation to evaluate the model

<h3>Mean Absolute Error</h3>
Using mean absolute error of the model as scoring for hold-out validation <i>(the best value is 0.0)</i>

In [531]:
sel_MAE_holdout = mean_absolute_error(Y_sel_test, Y_sel_pred)
color = "\033[92m" if sel_MAE_holdout < 0.5 else "\033[91m"

print( f"Selected Feastures Mean Absolute Error of Holdout: \033[1m{color}{sel_MAE_holdout}\033[0m")

Selected Feastures Mean Absolute Error of Holdout: 4465264888.972297

<h3>Mean Squared Error</h3>
Using mean squared error of the model as scoring for hold-out validation <i>(the best value is 0.0)</i>

In [532]:
sel_MSE_holdout = mean_squared_error(Y_sel_test, Y_sel_pred)
color = "\033[92m" if sel_MSE_holdout < 0.5 else "\033[91m"

print( f"Selected Feastures Mean Squared Error of Holdout: \033[1m{color}{sel_MSE_holdout}\033[0m")

Selected Feastures Mean Squared Error of Holdout: 3.923648980697128e+20

<h3>R-Squared Error</h3>
Using r-squared error of the model as scoring for hold-out validation <i>(the best value is 1.0)</i>

In [533]:
sel_R2_holdout = r2_score(Y_sel_test, Y_sel_pred)
color = "\033[92m" if sel_R2_holdout > 0.5 else "\033[91m"

print( f"Selected Feastures R2 of Holdout: \033[1m{color}{sel_R2_holdout}\033[0m")

Selected Feastures R2 of Holdout: -1.384163971911691e+22

<h3>Explained Variance Score</h3>
Using explained variance score of the model as scoring for hold-out validation  <i>(the best value is 1.0)</i>

In [534]:
sel_EV_holdout = explained_variance_score(Y_sel_test, Y_sel_pred)
color = "\033[92m" if sel_EV_holdout > 0.5 else "\033[91m"

print( f"Selected Feastures Explained Variance of Holdout: \033[1m{color}{sel_EV_holdout}\033[0m")

Selected Feastures Explained Variance of Holdout: -1.3694549012421785e+22

<h3>Root Mean Squared Error</h3>
Using root mean squared error of the model as scoring for hold-out validation  <i>(the best value is 0.0)</i>

In [535]:
sel_RMSE_holdout = np.sqrt(sel_MSE_holdout)
color = "\033[92m" if sel_RMSE_holdout < 0.5 else "\033[91m"

print( f"Selected Feastures Root Mean Squared Error of Holdout: \033[1m{color}{sel_RMSE_holdout}\033[0m")

Selected Feastures Root Mean Squared Error of Holdout: 19808202797.571335

# CONCLUSION
Based on the results, the model with the **selected features** performed better than the model with all the features. <br>
The model with the **selected features** has a lower **mean absolute error**, **mean squared error**, **root mean squared error**, and higher **R2** and **explained variance**.

The **Linear Regression** model was the worst performing model ever tested using this dataset, while the **Decision Tree Regression** model was the best model for this dataset, with the **Random Forest Regression** model being the 2nd and **Support Vector Regression** model being the 3rd.

<center>
    <h1><b>OPTIMIZATION</b></h1>
</center>

<h2>GridSearchCV</h2>
Applying GridSearchCV to find the Best Parameters for the Linear Regression Model

In [536]:
# linear regression parameters
parameters = {
    'fit_intercept': [True, False],
    'copy_X': [True, False],
    'n_jobs': [None, 1, 2, 3, 4, 5, 6],
    'positive': [True, False],
}

# Create GridSearchCV object
sel_grid_search = GridSearchCV(estimator=LinearRegression(),
                           param_grid=parameters,
                           scoring='r2',  # Use R-squared as the scoring metric
                           cv=10,  # You can adjust the number of folds in cross-validation
                           n_jobs=-1)

# Fit the grid search to the data
sel_grid_search = sel_grid_search.fit(X_sel, Y_sel)

print(f"CV RESULTS:")
display(pd.DataFrame(sel_grid_search.cv_results_)[['mean_test_score', 'std_test_score', 'params']])


color = "\033[92m" if sel_grid_search.best_score_ > 0.5 else "\033[91m"
print(f"BEST ACCURACY SCORE (1.0 is best): \n\033[1m{color}{sel_grid_search.best_score_}\033[0m\n")

print(f"BEST PARAMETERS:")
display(pd.DataFrame(sel_grid_search.best_params_, index=[0]))

CV RESULTS:

,mean_test_score,std_test_score,params
0,8.134361e-01,1.668099e-01,"{'copy_X': True, 'fit_intercept': True, 'n_job..."
1,-3.062165e+24,4.776507e+24,"{'copy_X': True, 'fit_intercept': True, 'n_job..."
2,8.134361e-01,1.668099e-01,"{'copy_X': True, 'fit_intercept': True, 'n_job..."
3,-3.062165e+24,4.776507e+24,"{'copy_X': True, 'fit_intercept': True, 'n_job..."
4,8.134361e-01,1.668099e-01,"{'copy_X': True, 'fit_intercept': True, 'n_job..."
5,-3.062165e+24,4.776507e+24,"{'copy_X': True, 'fit_intercept': True, 'n_job..."
6,8.134361e-01,1.668099e-01,"{'copy_X': True, 'fit_intercept': True, 'n_job..."
7,-3.062165e+24,4.776507e+24,"{'copy_X': True, 'fit_intercept': True, 'n_job..."
8,8.134361e-01,1.668099e-01,"{'copy_X': True, 'fit_intercept': True, 'n_job..."
9,-3.062165e+24,4.776507e+24,"{'copy_X': True, 'fit_intercept': True, 'n_job..."
10,8.134361e-01,1.668099e-01,"{'copy_X': True, 'fit_intercept': True, 'n_job..."
11,-3.062165e+24,4.776507e+24,"{'copy_X': True, 'fit_intercept': True, 'n_job..."
12,8.134361e-01,1.668099e-01,"{'copy_X': True, 'fit_intercept': True, 'n_job..."
13,-3.062165e+24,4.776507e+24,"{'copy_X': True, 'fit_intercept': True, 'n_job..."
14,8.115329e-01,1.699449e-01,"{'copy_X': True, 'fit_intercept': False, 'n_jo..."
15,-1.270872e+21,1.813914e+21,"{'copy_X': True, 'fit_intercept': False, 'n_jo..."
16,8.115329e-01,1.699449e-01,"{'copy_X': True, 'fit_intercept': False, 'n_jo..."
17,-1.270872e+21,1.813914e+21,"{'copy_X': True, 'fit_intercept': False, 'n_jo..."
18,8.115329e-01,1.699449e-01,"{'copy_X': True, 'fit_intercept': False, 'n_jo..."
19,-1.270872e+21,1.813914e+21,"{'copy_X': True, 'fit_intercept': False, 'n_jo..."
20,8.115329e-01,1.699449e-01,"{'copy_X': True, 'fit_intercept': False, 'n_jo..."
21,-1.270872e+21,1.813914e+21,"{'copy_X': True, 'fit_intercept': False, 'n_jo..."
22,8.115329e-01,1.699449e-01,"{'copy_X': True, 'fit_intercept': False, 'n_jo..."
23,-1.270872e+21,1.813914e+21,"{'copy_X': True, 'fit_intercept': False, 'n_jo..."
24,8.115329e-01,1.699449e-01,"{'copy_X': True, 'fit_intercept': False, 'n_jo..."
25,-1.270872e+21,1.813914e+21,"{'copy_X': True, 'fit_intercept': False, 'n_jo..."
26,8.115329e-01,1.699449e-01,"{'copy_X': True, 'fit_intercept': False, 'n_jo..."
27,-1.270872e+21,1.813914e+21,"{'copy_X': True, 'fit_intercept': False, 'n_jo..."
28,8.134361e-01,1.668099e-01,"{'copy_X': False, 'fit_intercept': True, 'n_jo..."
29,-3.062165e+24,4.776507e+24,"{'copy_X': False, 'fit_intercept': True, 'n_jo..."
30,8.134361e-01,1.668099e-01,"{'copy_X': False, 'fit_intercept': True, 'n_jo..."
31,-3.062165e+24,4.776507e+24,"{'copy_X': False, 'fit_intercept': True, 'n_jo..."
32,8.134361e-01,1.668099e-01,"{'copy_X': False, 'fit_intercept': True, 'n_jo..."
33,-3.062165e+24,4.776507e+24,"{'copy_X': False, 'fit_intercept': True, 'n_jo..."
34,8.134361e-01,1.668099e-01,"{'copy_X': False, 'fit_intercept': True, 'n_jo..."
35,-3.062165e+24,4.776507e+24,"{'copy_X': False, 'fit_intercept': True, 'n_jo..."
36,8.134361e-01,1.668099e-01,"{'copy_X': False, 'fit_intercept': True, 'n_jo..."
37,-3.062165e+24,4.776507e+24,"{'copy_X': False, 'fit_intercept': True, 'n_jo..."
38,8.134361e-01,1.668099e-01,"{'copy_X': False, 'fit_intercept': True, 'n_jo..."
39,-3.062165e+24,4.776507e+24,"{'copy_X': False, 'fit_intercept': True, 'n_jo..."
40,8.134361e-01,1.668099e-01,"{'copy_X': False, 'fit_intercept': True, 'n_jo..."
41,-3.062165e+24,4.776507e+24,"{'copy_X': False, 'fit_intercept': True, 'n_jo..."
42,8.115329e-01,1.699449e-01,"{'copy_X': False, 'fit_intercept': False, 'n_j..."
43,-1.270872e+21,1.813914e+21,"{'copy_X': False, 'fit_intercept': False, 'n_j..."
44,8.115329e-01,1.699449e-01,"{'copy_X': False, 'fit_intercept': False, 'n_j..."
45,-1.270872e+21,1.813914e+21,"{'copy_X': False, 'fit_intercept': False, 'n_j..."
46,8.115329e-01,1.699449e-01,"{'copy_X': False, 'fit_intercept': False, 'n_j..."
47,-1.270872e+21,1.813914e+21,"{'copy_X': False, 'fit_intercept': False, 'n_j..."
48,8.115329e-01,1.699449e-01,"{'copy_X': False, 'fit_intercept': False, 'n_j..."
49,-1.270872e+21,1.813914e+21,"{'copy_X': False, 'fit_intercept': False, 'n_j..."
50,8.115329e-01,1.699449e-01,"{'copy_X': False, 'fit_intercept': False, 'n_j..."
51,-1.270872e+21,1.813914e+21,"{'copy_X': False, 'fit_intercept': False, 'n_j..."
52,8.115329e-01,1.699449e-01,"{'copy_X': False, 'fit_intercept': False, 'n_j..."
53,-1.270872e+21,1.813914e+21,"{'copy_X': False, 'fit_intercept': False, 'n_j..."
54,8.115329e-01,1.699449e-01,"{'copy_X': False, 'fit_intercept': False, 'n_j..."
55,-1.270872e+21,1.813914e+21,"{'copy_X': False, 'fit_intercept': False, 'n_j..."

BEST ACCURACY SCORE (1.0 is best):
0.8134360630703226

BEST PARAMETERS:

   copy_X  fit_intercept n_jobs  positive
0    True           True   None      True

<h2>New Linear Regression Model with Optimized Parameters</h2>
Create a linear regression model with the optimized parameters

In [537]:
#use the values from sel_grid_search.best_score_
sel_linear_regression_optimized = LinearRegression(**sel_grid_search.best_params_)
sel_linear_regression_optimized.fit(X_sel_train, Y_sel_train)

LinearRegression(positive=True)

<h2>Prediction Capabilities</h2>
Check the prediction capabilities of optimized parameters

In [538]:
Y_sel_pred_optimized = sel_linear_regression_optimized.predict(X_sel_test)

# show the comparison between the actual and predicted values
pd.DataFrame({'Actual': Y_sel_test, 'Predicted': Y_sel_pred_optimized}).head(20).applymap('{:f}'.format)

      Actual Predicted
0   0.188715  0.201297
1   0.390708  0.324475
2   0.168847  0.218465
3   0.164211  0.148721
4   0.294679  0.304622
5   0.196993  0.184612
6   0.198649  0.149293
7   0.123812  0.121508
8   0.092685  0.087403
9   0.540382  0.540382
10  0.196993  0.173931
11  0.304613  0.284610
12  0.112583  0.119421
13  0.220173  0.192244
14  0.288056  0.282712
15  0.185404  0.202379
16  1.000000  0.855588
17  0.208583  0.203079
18  0.284745  0.283018
19  0.211894  0.223733

<h2>K-Fold Cross Validation</h2>
Use k-fold cross validation to get the accuracy of the model

In [539]:
sel_kfold_optimized = KFold(n_splits=10, random_state=0, shuffle=True)

<h3>Mean Absolute Error</h3>
Using mean absolute error of the model as scoring for cross validation

In [540]:
# calculate the mean absolute error of the model as scoring for cross validation
sel_MAE = -cross_val_score(sel_linear_regression_optimized, X_sel, Y_sel, cv=sel_kfold_optimized, scoring='neg_mean_absolute_error')

print(f"Selected Feastures Mean Absolute Error of k-Folds: \033[1m\033[94m{(sel_MAE)}\033[0m")
print(f"Average Selected Feastures Mean Absolute Error of k-Folds: \033[1m\033[94m{(sel_MAE.mean())}\033[0m")
print(f"Standard Deviation of Selected Feastures Mean Absolute Error of k-Folds: \033[1m\033[94m{(sel_MAE.std())}\033[0m")

Selected Feastures Mean Absolute Error of k-Folds: [0.038006 0.026176 0.025518 0.025786 0.017046 0.032728 0.021597 0.018459
 0.023935 0.022488]
Average Selected Feastures Mean Absolute Error of k-Folds: 0.025173977929237496
Standard Deviation of Selected Feastures Mean Absolute Error of k-Folds: 0.005965916873218685

<h3>Mean Squared Error</h3>
Using mean squared error of the model as scoring for cross validation

In [541]:
sel_MSE = -cross_val_score(sel_linear_regression_optimized, X_sel, Y_sel, cv=sel_kfold_optimized, scoring='neg_mean_squared_error')

print( f"Selected Feastures Mean Squared Error of k-Folds: \033[1m\033[94m{(sel_MSE)}\033[0m")
print( f"Average Selected Feastures Mean Squared Error of k-Folds: \033[1m\033[94m{(sel_MSE.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures Mean Squared Error of k-Folds: \033[1m\033[94m{(sel_MSE.std())}\033[0m")

Selected Feastures Mean Squared Error of k-Folds: [0.007844 0.001440 0.003663 0.001432 0.000648 0.006445 0.001047 0.000658
 0.001097 0.000987]
Average Selected Feastures Mean Squared Error of k-Folds: 0.00252618712893998
Standard Deviation of Selected Feastures Mean Squared Error of k-Folds: 0.0024682749782704992

<h3>R-Squared</h3>
Using r-squared of the model as scoring for cross validation

In [542]:
sel_R2 = cross_val_score(sel_linear_regression_optimized, X_sel, Y_sel, cv=sel_kfold, scoring='r2')

print( f"Selected Feastures R2 of k-Folds: \033[1m\033[94m{(sel_R2)}\033[0m")
print( f"Average Selected Feastures R2 of k-Folds: \033[1m\033[94m{(sel_R2.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures R2 of k-Folds: \033[1m\033[94m{(sel_R2.std())}\033[0m")

Selected Feastures R2 of k-Folds: [0.761174 0.939135 0.719779 0.888699 0.942186 0.685668 0.906883 0.951957
 0.918219 0.893791]
Average Selected Feastures R2 of k-Folds: 0.860749168517715
Standard Deviation of Selected Feastures R2 of k-Folds: 0.0942551830452772

<h3>Explained Variance Score</h3>
Using explained variance score of the model as scoring for cross validation

In [543]:
sel_EV = cross_val_score(sel_linear_regression_optimized, X_sel, Y_sel, cv=sel_kfold, scoring='explained_variance')

print( f"Selected Feastures Explained Variance of k-Folds: \033[1m\033[94m{(sel_EV)}\033[0m")
print( f"Average Selected Feastures Explained Variance of k-Folds: \033[1m\033[94m{(sel_EV.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures Explained Variance of k-Folds: \033[1m\033[94m{(sel_EV.std())}\033[0m")

Selected Feastures Explained Variance of k-Folds: [0.779631 0.940836 0.720857 0.891917 0.942191 0.697496 0.908171 0.956347
 0.919602 0.893967]
Average Selected Feastures Explained Variance of k-Folds: 0.8651013623363699
Standard Deviation of Selected Feastures Explained Variance of k-Folds: 0.0908764360060972

<h3>Root Mean Squared Error</h3>
Using root mean squared error of the model as scoring for cross validation

In [544]:
sel_RMSE = np.sqrt(sel_MSE)

print( f"Selected Feastures Root Mean Squared Error: \033[1m\033[94m{(sel_RMSE)}\033[0m")
print( f"Average Selected Feastures Root Mean Squared Error: \033[1m\033[94m{(sel_RMSE.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures Root Mean Squared Error: \033[1m\033[94m{(sel_RMSE.std())}\033[0m")

Selected Feastures Root Mean Squared Error: [0.088568 0.037948 0.060522 0.037844 0.025449 0.080280 0.032365 0.025653
 0.033117 0.031424]
Average Selected Feastures Root Mean Squared Error: 0.045317147650179794
Standard Deviation of Selected Feastures Root Mean Squared Error: 0.021738060120254137

<h2>Hold-Out Validation</h2>
Use hold-out validation to evaluate the model

<h3>Mean Absolute Error</h3>
Using mean absolute error of the model as scoring for hold-out validation <i>(the best value is 0.0)</i>

In [545]:
sel_MAE_holdout = mean_absolute_error(Y_sel_test, Y_sel_pred_optimized)
color = "\033[92m" if sel_MAE_holdout < 0.5 else "\033[91m"

print( f"Selected Feastures Mean Absolute Error of Holdout: \033[1m{color}{(sel_MAE_holdout)}\033[0m")

Selected Feastures Mean Absolute Error of Holdout: 0.03113040754728864

<h3>Mean Squared Error</h3>
Using mean squared error of the model as scoring for hold-out validation <i>(the best value is 0.0)</i>

In [546]:
sel_MSE_holdout = mean_squared_error(Y_sel_test, Y_sel_pred_optimized)
color = "\033[92m" if sel_MSE_holdout < 0.5 else "\033[91m"

print( f"Selected Feastures Mean Squared Error of Holdout: \033[1m{color}{(sel_MSE_holdout)}\033[0m")

Selected Feastures Mean Squared Error of Holdout: 0.004518258521529719

<h3>R-Squared Error</h3>
Using r-squared error of the model as scoring for hold-out validation <i>(the best value is 1.0)</i>

In [547]:
sel_R2_holdout = r2_score(Y_sel_test, Y_sel_pred_optimized)
color = "\033[92m" if sel_R2_holdout > 0.5 else "\033[91m"

print( f"Selected Feastures R2 of Holdout: \033[1m{color}{(sel_R2_holdout)}\033[0m")

Selected Feastures R2 of Holdout: 0.8406072843913461

<h3>Explained Variance Score</h3>
Using explained variance score of the model as scoring for hold-out validation  <i>(the best value is 1.0)</i>

In [548]:
sel_EV_holdout = explained_variance_score(Y_sel_test, Y_sel_pred_optimized)
color = "\033[92m" if sel_EV_holdout > 0.5 else "\033[91m"

print( f"Selected Feastures Explained Variance of Holdout: \033[1m{color}{(sel_EV_holdout)}\033[0m")

Selected Feastures Explained Variance of Holdout: 0.848776571053038

<h3>Root Mean Squared Error</h3>
Using root mean squared error of the model as scoring for hold-out validation  <i>(the best value is 0.0)</i>

In [549]:
sel_RMSE_holdout = np.sqrt(sel_MSE_holdout)
color = "\033[92m" if sel_RMSE_holdout < 0.5 else "\033[91m"

print( f"Selected Feastures Root Mean Squared Error of Holdout: \033[1m{color}{(sel_RMSE_holdout)}\033[0m")

Selected Feastures Root Mean Squared Error of Holdout: 0.0672179925431407

# CONCLUSION
Optimization succeeded, the model is now better than before but still not good enough 
to be used in production. We will try to use a different model to see if it can improve
the results.