<center>
    <h1><strong>GROUP 11</strong></h1>
    <h2>The Decision Tree Regression Model</h2>
</center>

<h3>Group Members</h3>
Onte, Michael Jethro M.<br>
Sunga, Jullianne Christille N.<br>
Villegas, Renz Justine L.<br>

<h1>Importing Required Libraries</h1>
This file contains all the libraries that are required for the project.

In [255]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, explained_variance_score, r2_score
# import decision tree regressor
from sklearn.tree import DecisionTreeRegressor

# for showing the proper table
from IPython.display import display

<h1>Loading and Viewing Data for Cross Validation in 10 folds</h1>
Import the database for all the features.

In [256]:
# read the data
df_norm = pd.read_csv('Group 11_CompleteDataset.csv')
df_norm

,Dedicated Graphic Memory Capacity,SSD Capacity,RAM,Clock Speed,Cache,Number of Cores,Screen Size,Screen Resolution,Wireless LAN,Bluetooth,...,Brand_dell,Brand_hp,Brand_infinix,Brand_lenovo,Brand_mi,Brand_msi,Brand_nokia,Brand_redmibook,Brand_vaio,Price
0,0.50,0.50,1.000,0.961538,1.000000,1.000000,1.000000,0.400000,1.000000,0.866667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.778138
1,0.50,0.50,1.000,0.961538,1.000000,1.000000,0.901684,0.400000,1.000000,0.866667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.761581
2,0.25,0.25,0.500,0.846154,0.666667,0.571429,0.930587,0.225000,1.000000,0.866667,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.344684
3,0.25,0.25,0.500,0.615385,0.666667,0.571429,0.901684,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.290463
4,0.00,0.25,0.500,0.461538,0.333333,0.285714,0.809285,0.225000,1.000000,0.833333,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.259595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,0.00,0.25,0.500,0.942308,0.333333,0.285714,0.809285,0.400000,0.833333,0.850000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.711149
647,0.00,0.25,0.250,0.807692,0.250000,0.285714,0.809285,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.178781
648,0.00,0.25,0.500,0.865385,0.333333,0.285714,0.768776,0.225000,1.000000,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.793930
649,0.00,0.25,0.250,0.769231,0.125000,0.428571,0.768776,0.225000,0.833333,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.283304
650,0.00,0.00,0.125,0.692308,0.041667,0.142857,0.809285,0.113833,0.833333,0.683333,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.147654

<h2>Independent and Dependent Variables.</h2>
Creates a matrix of independent variables and a matrix of dependent variables.

In [257]:

# create a matrix of dependent variables
X_norm = df_norm.drop(['Price'], axis=1).values

print("Normal Independent Variable Array:")
display(pd.DataFrame(X_norm))

# create a matrix of independent variables
y_norm = df_norm['Price'].values

print("Normal Dependent Variable Array:")
display(pd.DataFrame(y_norm))

Normal Independent Variable Array:

,0,1,2,3,4,5,6,7,8,9,...,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040
0,0.50,0.50,1.000,0.961538,1.000000,1.000000,1.000000,0.400000,1.000000,0.866667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.50,0.50,1.000,0.961538,1.000000,1.000000,0.901684,0.400000,1.000000,0.866667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.25,0.25,0.500,0.846154,0.666667,0.571429,0.930587,0.225000,1.000000,0.866667,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.25,0.25,0.500,0.615385,0.666667,0.571429,0.901684,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.25,0.500,0.461538,0.333333,0.285714,0.809285,0.225000,1.000000,0.833333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,0.00,0.25,0.500,0.942308,0.333333,0.285714,0.809285,0.400000,0.833333,0.850000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
647,0.00,0.25,0.250,0.807692,0.250000,0.285714,0.809285,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
648,0.00,0.25,0.500,0.865385,0.333333,0.285714,0.768776,0.225000,1.000000,0.833333,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
649,0.00,0.25,0.250,0.769231,0.125000,0.428571,0.768776,0.225000,0.833333,0.833333,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
650,0.00,0.00,0.125,0.692308,0.041667,0.142857,0.809285,0.113833,0.833333,0.683333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

Normal Dependent Variable Array:

            0
0    0.778138
1    0.761581
2    0.344684
3    0.290463
4    0.259595
..        ...
646  0.711149
647  0.178781
648  0.793930
649  0.283304
650  0.147654

[651 rows x 1 columns]

<h2>Training and Testing Datasets</h2>
Split the data into training and testing datasets

In [258]:
X_norm_train, X_norm_test, Y_norm_train, Y_norm_test = train_test_split(X_norm, y_norm, test_size=0.2, random_state=0)

print("Normal X Train:")
display(pd.DataFrame(X_norm_train))

print("Normal X Test:")
display(pd.DataFrame(X_norm_test))

print("Normal Y Train:")
display(pd.DataFrame(Y_norm_train))

print("Normal Y Test:")
display(pd.DataFrame(Y_norm_test))

Normal X Train:

,0,1,2,3,4,5,6,7,8,9,...,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040
0,0.00,0.125,0.250,0.788462,0.250000,0.142857,0.864816,0.225000,0.833333,0.683333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.25,0.125,0.500,0.961538,0.666667,0.571429,0.901684,0.225000,1.000000,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.00,0.250,0.500,0.807692,0.333333,0.285714,0.809285,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.00,0.000,0.250,0.692308,0.250000,0.285714,0.901684,0.225000,0.833333,0.683333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.125,0.250,0.673077,0.208333,0.142857,0.901684,0.225000,0.833333,0.700000,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,0.00,0.250,0.500,0.807692,0.333333,0.571429,0.774693,0.225000,1.000000,0.850000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
516,0.00,0.000,0.250,0.692308,0.250000,0.285714,0.901684,0.225000,0.833333,0.683333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
517,0.00,0.250,0.500,0.865385,0.333333,0.285714,0.809285,0.225000,1.000000,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
518,0.00,0.250,0.250,0.711538,0.250000,0.285714,0.901684,0.225000,0.833333,0.700000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
519,0.00,0.000,0.125,0.653846,0.166667,0.142857,0.901684,0.113833,0.833333,0.683333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Normal X Test:

,0,1,2,3,4,5,6,7,8,9,...,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040
0,0.000,0.250,0.250,0.807692,0.333333,0.285714,0.809285,0.225000,1.000000,0.850000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.250,0.250,0.500,0.884615,1.000000,0.571429,0.901684,0.225000,1.000000,0.850000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.000,0.250,0.500,0.750000,0.333333,0.285714,0.809285,0.225000,1.000000,0.850000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000,0.250,0.250,0.711538,0.250000,0.285714,0.901684,0.225000,0.833333,0.700000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.125,0.250,0.500,0.807692,0.333333,0.285714,0.809285,0.444444,0.833333,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,0.000,0.125,0.125,0.596154,0.166667,0.285714,0.901684,0.225000,0.833333,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
127,0.125,0.250,0.250,0.807692,0.250000,0.285714,0.809285,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
128,0.000,0.000,0.125,0.692308,0.041667,0.142857,0.809285,0.113833,0.833333,0.683333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
129,0.000,0.125,0.250,0.673077,0.166667,0.142857,0.864816,0.225000,0.833333,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
130,0.000,0.125,0.250,0.788462,0.250000,0.142857,0.901684,0.225000,1.000000,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Normal Y Train:

            0
0    0.129110
1    0.228451
2    0.165535
3    0.148978
4    0.137389
..        ...
515  0.495530
516  0.148978
517  0.235074
518  0.168847
519  0.112553

[520 rows x 1 columns]

Normal Y Test:

            0
0    0.188715
1    0.390708
2    0.168847
3    0.164211
4    0.294679
..        ...
126  0.119209
127  0.182122
128  0.147654
129  0.115865
130  0.168847

[131 rows x 1 columns]

<h1>Decision Tree Regression Model</h1>
Create a decision tree regressor model then fit the training datasets

In [259]:
# create a decision tree regressor model
norm_decision_tree = DecisionTreeRegressor()
norm_decision_tree.fit(X_norm_train, Y_norm_train)

# predict the test set results
Y_norm_pred = norm_decision_tree.predict(X_norm_test)

<h2>K-Fold Cross Validation</h2>
Use k-fold cross validation to get the accuracy of the model

In [260]:
norm_kfold = KFold(n_splits=10, random_state=0, shuffle=True)

<h3>Mean Absolute Error</h3>
Using mean absolute error of the model as scoring for cross validation

In [261]:
# calculate the mean absolute error of the model as scoring for cross validation
norm_MAE = -cross_val_score(norm_decision_tree, X_norm, y_norm, cv=norm_kfold, scoring='neg_mean_absolute_error')


print( f"Normal Mean Absolute Error of k-Folds: \033[1m\033[94m{(norm_MAE)}\033[0m")
print( f"Average Normal Mean Absolute Error of k-Folds: \033[1m\033[94m{(norm_MAE.mean())}\033[0m")
print( f"Standard Deviation of Normal Mean Absolute Error of k-Folds: \033[1m\033[94m{(norm_MAE.std())}\033[0m")

Normal Mean Absolute Error of k-Folds: [0.04173613 0.02778223 0.0293299  0.03283884 0.0218397  0.03960482
 0.03256231 0.02746459 0.03230244 0.02769312]
Average Normal Mean Absolute Error of k-Folds: 0.031315408857256935
Standard Deviation of Normal Mean Absolute Error of k-Folds: 0.0056242348913778705

<h3>Mean Squared Error</h3>
Using mean squared error of the model as scoring for cross validation

In [262]:
norm_MSE = -cross_val_score(norm_decision_tree, X_norm, y_norm, cv=norm_kfold, scoring='neg_mean_squared_error')

print( f"Normal Mean Squared Error of k-Folds: \033[1m\033[94m{(norm_MSE)}\033[0m")
print( f"Average Normal Mean Squared Error of k-Folds: \033[1m\033[94m{(norm_MSE.mean())}\033[0m")
print( f"Standard Deviation of Normal Mean Squared Error of k-Folds: \033[1m\033[94m{(norm_MSE.std())}\033[0m")

Normal Mean Squared Error of k-Folds: [0.009116   0.00183907 0.00659207 0.00274618 0.00124273 0.00821931
 0.00310983 0.0027178  0.00307266 0.00226367]
Average Normal Mean Squared Error of k-Folds: 0.004091930813045458
Standard Deviation of Normal Mean Squared Error of k-Folds: 0.002660185566447144

<h3>R-Squared</h3>
Using r-squared of the model as scoring for cross validation

In [263]:
norm_R2 = cross_val_score(norm_decision_tree, X_norm, y_norm, cv=norm_kfold, scoring='r2')

print( f"Normal R2 of k-Folds: \033[1m\033[94m{(norm_R2)}\033[0m")
print( f"Average Normal R2 of k-Folds: \033[1m\033[94m{(norm_R2.mean())}\033[0m")
print( f"Standard Deviation of Normal R2 of k-Folds: \033[1m\033[94m{(norm_R2.std())}\033[0m")

Normal R2 of k-Folds: [0.71333708 0.93640141 0.53211464 0.80686262 0.87508129 0.54662203
 0.85888487 0.79055527 0.77319836 0.76092689]
Average Normal R2 of k-Folds: 0.7593984467263474
Standard Deviation of Normal R2 of k-Folds: 0.12533150583419161

<h3>Explained Variance Score</h3>
Using explained variance score of the model as scoring for cross validation

In [264]:
norm_EV = cross_val_score(norm_decision_tree, X_norm, y_norm, cv=norm_kfold, scoring='explained_variance')

print( f"Normal Explained Variance of k-Folds: \033[1m\033[94m{(norm_EV)}\033[0m")
print( f"Average Normal Explained Variance of k-Folds: \033[1m\033[94m{(norm_EV.mean())}\033[0m")
print( f"Standard Deviation of Normal Explained Variance of k-Folds: \033[1m\033[94m{(norm_EV.std())}\033[0m")

Normal Explained Variance of k-Folds: [0.73229112 0.93159575 0.53313591 0.79888678 0.90101745 0.56518772
 0.78959611 0.38935036 0.78398016 0.78101496]
Average Normal Explained Variance of k-Folds: 0.7206056318539028
Standard Deviation of Normal Explained Variance of k-Folds: 0.1627220721715126

<h3>Root Mean Squared Error</h3>
Using root mean squared error of the model as scoring for cross validation

In [265]:
norm_RMSE = np.sqrt(norm_MSE)

print( f"Normal Root Mean Squared Error: \033[1m\033[94m{(norm_RMSE)}\033[0m")
print( f"Average Normal Root Mean Squared Error: \033[1m\033[94m{(norm_RMSE.mean())}\033[0m")
print( f"Standard Deviation of Normal Root Mean Squared Error: \033[1m\033[94m{(norm_RMSE.std())}\033[0m")

Normal Root Mean Squared Error: [0.09547773 0.04288434 0.08119158 0.05240397 0.03525236 0.09066043
 0.05576581 0.0521325  0.0554316  0.04757802]
Average Normal Root Mean Squared Error: 0.06087783391187892
Standard Deviation of Normal Root Mean Squared Error: 0.019642305140770578

<h2>Hold-Out Validation</h2>
Use hold-out validation to evaluate the model

<h3>Mean Absolute Error</h3>
Using mean absolute error of the model as scoring for hold-out validation <i>(the best value is 0.0)</i>

In [266]:
norm_MAE_holdout = mean_absolute_error(Y_norm_test, Y_norm_pred)
color = "\033[92m" if norm_MAE_holdout < 0.5 else "\033[91m"

print( f"Normal Mean Absolute Error of Holdout: \033[1m{color}{(norm_MAE_holdout)}\033[0m")

Normal Mean Absolute Error of Holdout: 0.03229276180013147

<h3>Mean Squared Error</h3>
Using mean squared error of the model as scoring for hold-out validation <i>(the best value is 0.0)</i>

In [267]:
norm_MSE_holdout = mean_squared_error(Y_norm_test, Y_norm_pred)
color = "\033[92m" if norm_MSE_holdout < 0.5 else "\033[91m"

print( f"Normal Mean Squared Error of Holdout: \033[1m{color}{(norm_MSE_holdout)}\033[0m")

Normal Mean Squared Error of Holdout: 0.005084525963651867

<h3>R-Squared Error</h3>
Using r-squared error of the model as scoring for hold-out validation <i>(the best value is 1.0)</i>

In [268]:
norm_R2_holdout = r2_score(Y_norm_test, Y_norm_pred)
color = "\033[92m" if norm_R2_holdout > 0.5 else "\033[91m"

print( f"Normal R2 of Holdout: \033[1m{color}{(norm_R2_holdout)}\033[0m")

Normal R2 of Holdout: 0.8206308034240603

<h3>Explained Variance Score</h3>
Using explained variance score of the model as scoring for hold-out validation  <i>(the best value is 1.0)</i>

In [269]:
norm_EV_holdout = explained_variance_score(Y_norm_test, Y_norm_pred)
color = "\033[92m" if norm_EV_holdout > 0.5 else "\033[91m"

print( f"Normal Explained Variance of Holdout: \033[1m{color}{(norm_EV_holdout)}\033[0m")

Normal Explained Variance of Holdout: 0.8315979943630986

<h3>Root Mean Squared Error</h3>
Using root mean squared error of the model as scoring for hold-out validation  <i>(the best value is 0.0)</i>

In [270]:
norm_RMSE_holdout = np.sqrt(norm_MSE_holdout)
color = "\033[92m" if norm_RMSE_holdout < 0.5 else "\033[91m"

print( f"Normal Root Mean Squared Error of Holdout: \033[1m{color}{(norm_RMSE_holdout)}\033[0m")

Normal Root Mean Squared Error of Holdout: 0.0713058620567192

<h1>Loading and Viewing Data for Cross Validation in 10 folds</h1>
Import the database with the features selected.

In [271]:
# read the data
df_sel = pd.read_csv('Group 11_Dataset.csv')
df_sel

,Dedicated Graphic Memory Capacity,SSD Capacity,RAM,Cache,Screen Resolution,Bluetooth,Weight,Brightness,Refresh Rate,HDD Capacity,...,Warranty Summary_3 Year Carry-In Warranty,Warranty Summary_3 Year Premier Support Warranty,Brand_asus,Brand_dell,Brand_hp,Brand_infinix,Brand_lenovo,Brand_msi,Brand_redmibook,Price
0,0.50,0.50,1.000,1.000000,0.400000,0.866667,1.000000,0.500000,0.166667,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.778138
1,0.50,0.50,1.000,1.000000,0.400000,0.866667,0.793103,0.500000,0.166667,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.761581
2,0.25,0.25,0.500,0.666667,0.225000,0.866667,0.855172,0.500000,0.400000,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.344684
3,0.25,0.25,0.500,0.666667,0.225000,0.833333,0.775862,0.416667,0.333333,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.290463
4,0.00,0.25,0.500,0.333333,0.225000,0.833333,0.468966,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.259595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,0.00,0.25,0.500,0.333333,0.400000,0.850000,0.375862,0.500000,0.166667,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.711149
647,0.00,0.25,0.250,0.250000,0.225000,0.833333,0.379310,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.178781
648,0.00,0.25,0.500,0.333333,0.225000,0.833333,0.513793,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.793930
649,0.00,0.25,0.250,0.125000,0.225000,0.833333,0.455172,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.283304
650,0.00,0.00,0.125,0.041667,0.113833,0.683333,0.551724,0.416667,0.166667,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.147654

<h2>Independent and Dependent Variables.</h2>
Creates a matrix of independent variables and a matrix of dependent variables.

In [272]:

# create a matrix of dependent variables
X_sel = df_sel.drop(['Price'], axis=1).values

print("selal Independent Variable Array:")
display(pd.DataFrame(X_sel))

# create a matrix of independent variables
y_sel = df_sel['Price'].values

print("selal Dependent Variable Array:")
display(pd.DataFrame(y_sel))

selal Independent Variable Array:

,0,1,2,3,4,5,6,7,8,9,...,275,276,277,278,279,280,281,282,283,284
0,0.50,0.50,1.000,1.000000,0.400000,0.866667,1.000000,0.500000,0.166667,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.50,0.50,1.000,1.000000,0.400000,0.866667,0.793103,0.500000,0.166667,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.25,0.25,0.500,0.666667,0.225000,0.866667,0.855172,0.500000,0.400000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.25,0.25,0.500,0.666667,0.225000,0.833333,0.775862,0.416667,0.333333,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.00,0.25,0.500,0.333333,0.225000,0.833333,0.468966,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,0.00,0.25,0.500,0.333333,0.400000,0.850000,0.375862,0.500000,0.166667,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
647,0.00,0.25,0.250,0.250000,0.225000,0.833333,0.379310,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
648,0.00,0.25,0.500,0.333333,0.225000,0.833333,0.513793,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
649,0.00,0.25,0.250,0.125000,0.225000,0.833333,0.455172,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
650,0.00,0.00,0.125,0.041667,0.113833,0.683333,0.551724,0.416667,0.166667,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

selal Dependent Variable Array:

            0
0    0.778138
1    0.761581
2    0.344684
3    0.290463
4    0.259595
..        ...
646  0.711149
647  0.178781
648  0.793930
649  0.283304
650  0.147654

[651 rows x 1 columns]

<h2>Training and Testing Datasets</h2>
Split the data into training and testing datasets

In [273]:
X_sel_train, X_sel_test, Y_sel_train, Y_sel_test = train_test_split(X_sel, y_sel, test_size=0.2, random_state=0)

print("Selected Features X Train:")
display(pd.DataFrame(X_sel_train))

print("Selected Features X Test:")
display(pd.DataFrame(X_sel_test))

print("Selected Features Y Train:")
display(pd.DataFrame(Y_sel_train))

print("Selected Features Y Test:")
display(pd.DataFrame(Y_sel_test))

Selected Features X Train:

,0,1,2,3,4,5,6,7,8,9,...,275,276,277,278,279,280,281,282,283,284
0,0.00,0.125,0.250,0.250000,0.225000,0.683333,0.544828,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.25,0.125,0.500,0.666667,0.225000,0.833333,0.737931,0.416667,0.333333,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.00,0.250,0.500,0.333333,0.225000,0.833333,0.482759,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.00,0.000,0.250,0.250000,0.225000,0.683333,0.620690,0.333333,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.125,0.250,0.208333,0.225000,0.700000,0.627586,0.416667,0.166667,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,0.00,0.250,0.500,0.333333,0.225000,0.850000,0.400000,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
516,0.00,0.000,0.250,0.250000,0.225000,0.683333,0.620690,0.416667,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
517,0.00,0.250,0.500,0.333333,0.225000,0.833333,0.503448,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
518,0.00,0.250,0.250,0.250000,0.225000,0.700000,0.610345,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
519,0.00,0.000,0.125,0.166667,0.113833,0.683333,0.620690,0.333333,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

Selected Features X Test:

,0,1,2,3,4,5,6,7,8,9,...,275,276,277,278,279,280,281,282,283,284
0,0.000,0.250,0.250,0.333333,0.225000,0.850000,0.479310,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.250,0.250,0.500,1.000000,0.225000,0.850000,0.827586,0.416667,0.333333,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.000,0.250,0.500,0.333333,0.225000,0.850000,0.510345,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.000,0.250,0.250,0.250000,0.225000,0.700000,0.610345,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.125,0.250,0.500,0.333333,0.444444,0.833333,0.465517,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,0.000,0.125,0.125,0.166667,0.225000,0.833333,0.620690,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
127,0.125,0.250,0.250,0.250000,0.225000,0.833333,0.465517,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
128,0.000,0.000,0.125,0.041667,0.113833,0.683333,0.551724,0.416667,0.166667,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
129,0.000,0.125,0.250,0.166667,0.225000,0.833333,0.620690,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
130,0.000,0.125,0.250,0.250000,0.225000,0.833333,0.620690,1.000000,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

Selected Features Y Train:

            0
0    0.129110
1    0.228451
2    0.165535
3    0.148978
4    0.137389
..        ...
515  0.495530
516  0.148978
517  0.235074
518  0.168847
519  0.112553

[520 rows x 1 columns]

Selected Features Y Test:

            0
0    0.188715
1    0.390708
2    0.168847
3    0.164211
4    0.294679
..        ...
126  0.119209
127  0.182122
128  0.147654
129  0.115865
130  0.168847

[131 rows x 1 columns]

<h1>Decision Tree Regression Model</h1>
Create a decision tree regressor model then fit the training datasets

In [274]:
# create a decision tree regressor model
sel_decision_tree = DecisionTreeRegressor()
sel_decision_tree.fit(X_sel_train, Y_sel_train)

# predict the test set results
Y_sel_pred = sel_decision_tree.predict(X_sel_test)

<h2>K-Fold Cross Validation</h2>
Use k-fold cross validation to get the accuracy of the model

In [275]:
sel_kfold = KFold(n_splits=10, random_state=0, shuffle=True)

<h3>Mean Absolute Error</h3>
Using mean absolute error of the model as scoring for cross validation

In [276]:
# calculate the mean absolute error of the model as scoring for cross validation
sel_MAE = -cross_val_score(sel_decision_tree, X_sel, y_sel, cv=sel_kfold, scoring='neg_mean_absolute_error')

print(f"Selected Feastures Mean Absolute Error of k-Folds: \033[1m\033[94m{(sel_MAE)}\033[0m")
print(f"Average Selected Feastures Mean Absolute Error of k-Folds: \033[1m\033[94m{(sel_MAE.mean())}\033[0m")
print(f"Standard Deviation of Selected Feastures Mean Absolute Error of k-Folds: \033[1m\033[94m{(sel_MAE.std())}\033[0m")

Selected Feastures Mean Absolute Error of k-Folds: [0.03365223 0.02763102 0.02005033 0.03494787 0.02186827 0.03886388
 0.02524735 0.02981    0.02830792 0.02513792]
Average Selected Feastures Mean Absolute Error of k-Folds: 0.028551679779935037
Standard Deviation of Selected Feastures Mean Absolute Error of k-Folds: 0.005614909162709093

<h3>Mean Squared Error</h3>
Using mean squared error of the model as scoring for cross validation

In [277]:
sel_MSE = -cross_val_score(sel_decision_tree, X_sel, y_sel, cv=sel_kfold, scoring='neg_mean_squared_error')

print( f"Selected Feastures Mean Squared Error of k-Folds: \033[1m\033[94m{(sel_MSE)}\033[0m")
print( f"Average Selected Feastures Mean Squared Error of k-Folds: \033[1m\033[94m{(sel_MSE.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures Mean Squared Error of k-Folds: \033[1m\033[94m{(sel_MSE.std())}\033[0m")

Selected Feastures Mean Squared Error of k-Folds: [0.00576629 0.00174712 0.00277688 0.00312743 0.00105742 0.00472652
 0.00154211 0.0022736  0.00240237 0.00183902]
Average Selected Feastures Mean Squared Error of k-Folds: 0.00272587647529804
Standard Deviation of Selected Feastures Mean Squared Error of k-Folds: 0.0014017576533019967

<h3>R-Squared</h3>
Using r-squared of the model as scoring for cross validation

In [278]:
sel_R2 = cross_val_score(sel_decision_tree, X_sel, y_sel, cv=sel_kfold, scoring='r2')

print( f"Selected Feastures R2 of k-Folds: \033[1m\033[94m{(sel_R2)}\033[0m")
print( f"Average Selected Feastures R2 of k-Folds: \033[1m\033[94m{(sel_R2.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures R2 of k-Folds: \033[1m\033[94m{(sel_R2.std())}\033[0m")

Selected Feastures R2 of k-Folds: [0.72884298 0.93126795 0.78073469 0.7636588  0.9215347  0.62452364
 0.7978446  0.82971272 0.81981372 0.7845189 ]
Average Selected Feastures R2 of k-Folds: 0.7982452701576153
Standard Deviation of Selected Feastures R2 of k-Folds: 0.08428405481541604

<h3>Explained Variance Score</h3>
Using explained variance score of the model as scoring for cross validation

In [279]:
sel_EV = cross_val_score(sel_decision_tree, X_sel, y_sel, cv=sel_kfold, scoring='explained_variance')

print( f"Selected Feastures Explained Variance of k-Folds: \033[1m\033[94m{(sel_EV)}\033[0m")
print( f"Average Selected Feastures Explained Variance of k-Folds: \033[1m\033[94m{(sel_EV.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures Explained Variance of k-Folds: \033[1m\033[94m{(sel_EV.std())}\033[0m")

Selected Feastures Explained Variance of k-Folds: [0.83217212 0.93766116 0.78483458 0.74549815 0.90848111 0.76536155
 0.85730814 0.85314174 0.80918689 0.79965284]
Average Selected Feastures Explained Variance of k-Folds: 0.8293298279017767
Standard Deviation of Selected Feastures Explained Variance of k-Folds: 0.05808997753307833

<h3>Root Mean Squared Error</h3>
Using root mean squared error of the model as scoring for cross validation

In [280]:
sel_RMSE = np.sqrt(sel_MSE)

print( f"Selected Feastures Root Mean Squared Error: \033[1m\033[94m{(sel_RMSE)}\033[0m")
print( f"Average Selected Feastures Root Mean Squared Error: \033[1m\033[94m{(sel_RMSE.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures Root Mean Squared Error: \033[1m\033[94m{(sel_RMSE.std())}\033[0m")

Selected Feastures Root Mean Squared Error: [0.07593608 0.04179853 0.05269609 0.05592343 0.03251806 0.06874969
 0.03926976 0.04768226 0.04901401 0.04288382]
Average Selected Feastures Root Mean Squared Error: 0.05064717303003776
Standard Deviation of Selected Feastures Root Mean Squared Error: 0.01267834134906674

<h2>Hold-Out Validation</h2>
Use hold-out validation to evaluate the model

<h3>Mean Absolute Error</h3>
Using mean absolute error of the model as scoring for hold-out validation <i>(the best value is 0.0)</i>

In [281]:
sel_MAE_holdout = mean_absolute_error(Y_sel_test, Y_sel_pred)
color = "\033[92m" if sel_MAE_holdout < 0.5 else "\033[91m"

print( f"Selected Feastures Mean Absolute Error of Holdout: \033[1m{color}{(sel_MAE_holdout)}\033[0m")

Selected Feastures Mean Absolute Error of Holdout: 0.03322980299026422

<h3>Mean Squared Error</h3>
Using mean squared error of the model as scoring for hold-out validation <i>(the best value is 0.0)</i>

In [282]:
sel_MSE_holdout = mean_squared_error(Y_sel_test, Y_sel_pred)
color = "\033[92m" if sel_MSE_holdout < 0.5 else "\033[91m"

print( f"Selected Feastures Mean Squared Error of Holdout: \033[1m{color}{(sel_MSE_holdout)}\033[0m")

Selected Feastures Mean Squared Error of Holdout: 0.0038668496964625937

<h3>R-Squared Error</h3>
Using r-squared error of the model as scoring for hold-out validation <i>(the best value is 1.0)</i>

In [283]:
sel_R2_holdout = r2_score(Y_sel_test, Y_sel_pred)
color = "\033[92m" if sel_R2_holdout > 0.5 else "\033[91m"

print( f"Selected Feastures R2 of Holdout: \033[1m{color}{(sel_R2_holdout)}\033[0m")

Selected Feastures R2 of Holdout: 0.8635873376804922

<h3>Explained Variance Score</h3>
Using explained variance score of the model as scoring for hold-out validation  <i>(the best value is 1.0)</i>

In [284]:
sel_EV_holdout = explained_variance_score(Y_sel_test, Y_sel_pred)
color = "\033[92m" if sel_EV_holdout > 0.5 else "\033[91m"

print( f"Selected Feastures Explained Variance of Holdout: \033[1m{color}{(sel_EV_holdout)}\033[0m")

Selected Feastures Explained Variance of Holdout: 0.8656982727264387

<h3>Root Mean Squared Error</h3>
Using root mean squared error of the model as scoring for hold-out validation  <i>(the best value is 0.0)</i>

In [285]:
sel_RMSE_holdout = np.sqrt(sel_MSE_holdout)
color = "\033[92m" if sel_RMSE_holdout < 0.5 else "\033[91m"

print( f"Selected Feastures Root Mean Squared Error of Holdout: \033[1m{color}{(sel_RMSE_holdout)}\033[0m")

Selected Feastures Root Mean Squared Error of Holdout: 0.06218399871721497

# CONCLUSION
Based on the results, the model with the **selected features** performed better than the model with all the features. <br>
The model with the **selected features** has a lower **mean absolute error**, **mean squared error**, **root mean squared error**, and higher **R2** and **explained variance**.

The **Decision Tree Regression** model was the best model for this dataset, with the **Random Forest Regression** model being the 2nd and **Support Vector Regression** model being the 3rd, while **Linear Regression** model being the worst.