<center>
    <h1><strong>GROUP 11</strong></h1>
    <h2>The Linear Regression Model</h2>
</center>

<h3>Group Members</h3>
Onte, Michael Jethro M.<br>
Sunga, Jullianne Christille N.<br>
Villegas, Renz Justine L.<br>

<h1>Importing Required Libraries</h1>
This file contains all the libraries that are required for the project.

In [246]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, explained_variance_score, r2_score
# import linear regression model
from sklearn.linear_model import LinearRegression

# for showing the proper table
from IPython.display import display

<h1>Loading and Viewing Data for Cross Validation in 10 folds</h1>
Import the database for all the features.

In [247]:
# read the data
df_norm = pd.read_csv('Group 11_CompleteDataset.csv')
df_norm

,Dedicated Graphic Memory Capacity,SSD Capacity,RAM,Clock Speed,Cache,Number of Cores,Screen Size,Screen Resolution,Wireless LAN,Bluetooth,...,Brand_dell,Brand_hp,Brand_infinix,Brand_lenovo,Brand_mi,Brand_msi,Brand_nokia,Brand_redmibook,Brand_vaio,Price
0,0.50,0.50,1.000,0.961538,1.000000,1.000000,1.000000,0.400000,1.000000,0.866667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.778138
1,0.50,0.50,1.000,0.961538,1.000000,1.000000,0.901684,0.400000,1.000000,0.866667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.761581
2,0.25,0.25,0.500,0.846154,0.666667,0.571429,0.930587,0.225000,1.000000,0.866667,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.344684
3,0.25,0.25,0.500,0.615385,0.666667,0.571429,0.901684,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.290463
4,0.00,0.25,0.500,0.461538,0.333333,0.285714,0.809285,0.225000,1.000000,0.833333,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.259595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,0.00,0.25,0.500,0.942308,0.333333,0.285714,0.809285,0.400000,0.833333,0.850000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.711149
647,0.00,0.25,0.250,0.807692,0.250000,0.285714,0.809285,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.178781
648,0.00,0.25,0.500,0.865385,0.333333,0.285714,0.768776,0.225000,1.000000,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.793930
649,0.00,0.25,0.250,0.769231,0.125000,0.428571,0.768776,0.225000,0.833333,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.283304
650,0.00,0.00,0.125,0.692308,0.041667,0.142857,0.809285,0.113833,0.833333,0.683333,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.147654

<h2>Independent and Dependent Variables.</h2>
Creates a matrix of independent variables and a matrix of dependent variables.

In [248]:

# create a matrix of dependent variables
X_norm = df_norm.drop(['Price'], axis=1).values

print("Normal Independent Variable Array:")
display(pd.DataFrame(X_norm))

# create a matrix of independent variables
y_norm = df_norm['Price'].values

print("Normal Dependent Variable Array:")
display(pd.DataFrame(y_norm))

Normal Independent Variable Array:

,0,1,2,3,4,5,6,7,8,9,...,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040
0,0.50,0.50,1.000,0.961538,1.000000,1.000000,1.000000,0.400000,1.000000,0.866667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.50,0.50,1.000,0.961538,1.000000,1.000000,0.901684,0.400000,1.000000,0.866667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.25,0.25,0.500,0.846154,0.666667,0.571429,0.930587,0.225000,1.000000,0.866667,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.25,0.25,0.500,0.615385,0.666667,0.571429,0.901684,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.25,0.500,0.461538,0.333333,0.285714,0.809285,0.225000,1.000000,0.833333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,0.00,0.25,0.500,0.942308,0.333333,0.285714,0.809285,0.400000,0.833333,0.850000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
647,0.00,0.25,0.250,0.807692,0.250000,0.285714,0.809285,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
648,0.00,0.25,0.500,0.865385,0.333333,0.285714,0.768776,0.225000,1.000000,0.833333,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
649,0.00,0.25,0.250,0.769231,0.125000,0.428571,0.768776,0.225000,0.833333,0.833333,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
650,0.00,0.00,0.125,0.692308,0.041667,0.142857,0.809285,0.113833,0.833333,0.683333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

Normal Dependent Variable Array:

            0
0    0.778138
1    0.761581
2    0.344684
3    0.290463
4    0.259595
..        ...
646  0.711149
647  0.178781
648  0.793930
649  0.283304
650  0.147654

[651 rows x 1 columns]

<h2>Training and Testing Datasets</h2>
Split the data into training and testing datasets

In [249]:
X_norm_train, X_norm_test, Y_norm_train, Y_norm_test = train_test_split(X_norm, y_norm, test_size=0.2, random_state=0)

print("Normal X Train:")
display(pd.DataFrame(X_norm_train))

print("Normal X Test:")
display(pd.DataFrame(X_norm_test))

print("Normal Y Train:")
display(pd.DataFrame(Y_norm_train))

print("Normal Y Test:")
display(pd.DataFrame(Y_norm_test))

Normal X Train:

,0,1,2,3,4,5,6,7,8,9,...,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040
0,0.00,0.125,0.250,0.788462,0.250000,0.142857,0.864816,0.225000,0.833333,0.683333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.25,0.125,0.500,0.961538,0.666667,0.571429,0.901684,0.225000,1.000000,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.00,0.250,0.500,0.807692,0.333333,0.285714,0.809285,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.00,0.000,0.250,0.692308,0.250000,0.285714,0.901684,0.225000,0.833333,0.683333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.125,0.250,0.673077,0.208333,0.142857,0.901684,0.225000,0.833333,0.700000,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,0.00,0.250,0.500,0.807692,0.333333,0.571429,0.774693,0.225000,1.000000,0.850000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
516,0.00,0.000,0.250,0.692308,0.250000,0.285714,0.901684,0.225000,0.833333,0.683333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
517,0.00,0.250,0.500,0.865385,0.333333,0.285714,0.809285,0.225000,1.000000,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
518,0.00,0.250,0.250,0.711538,0.250000,0.285714,0.901684,0.225000,0.833333,0.700000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
519,0.00,0.000,0.125,0.653846,0.166667,0.142857,0.901684,0.113833,0.833333,0.683333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Normal X Test:

,0,1,2,3,4,5,6,7,8,9,...,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040
0,0.000,0.250,0.250,0.807692,0.333333,0.285714,0.809285,0.225000,1.000000,0.850000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.250,0.250,0.500,0.884615,1.000000,0.571429,0.901684,0.225000,1.000000,0.850000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.000,0.250,0.500,0.750000,0.333333,0.285714,0.809285,0.225000,1.000000,0.850000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000,0.250,0.250,0.711538,0.250000,0.285714,0.901684,0.225000,0.833333,0.700000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.125,0.250,0.500,0.807692,0.333333,0.285714,0.809285,0.444444,0.833333,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,0.000,0.125,0.125,0.596154,0.166667,0.285714,0.901684,0.225000,0.833333,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
127,0.125,0.250,0.250,0.807692,0.250000,0.285714,0.809285,0.225000,0.833333,0.833333,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
128,0.000,0.000,0.125,0.692308,0.041667,0.142857,0.809285,0.113833,0.833333,0.683333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
129,0.000,0.125,0.250,0.673077,0.166667,0.142857,0.864816,0.225000,0.833333,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
130,0.000,0.125,0.250,0.788462,0.250000,0.142857,0.901684,0.225000,1.000000,0.833333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Normal Y Train:

            0
0    0.129110
1    0.228451
2    0.165535
3    0.148978
4    0.137389
..        ...
515  0.495530
516  0.148978
517  0.235074
518  0.168847
519  0.112553

[520 rows x 1 columns]

Normal Y Test:

            0
0    0.188715
1    0.390708
2    0.168847
3    0.164211
4    0.294679
..        ...
126  0.119209
127  0.182122
128  0.147654
129  0.115865
130  0.168847

[131 rows x 1 columns]

<h1>Linear Regression Model</h1>
Create a linear regression model then fit the training datasets

In [250]:
# create a linear regression model
norm_linear_regression = LinearRegression()
norm_linear_regression.fit(X_norm_train, Y_norm_train)

# predict the test set results
Y_norm_pred = norm_linear_regression.predict(X_norm_test)

<h2>K-Fold Cross Validation</h2>
Use k-fold cross validation to get the accuracy of the model

In [251]:
norm_kfold = KFold(n_splits=10, random_state=0, shuffle=True)

<h3>Mean Absolute Error</h3>
Using mean absolute error of the model as scoring for cross validation

In [252]:
# calculate the mean absolute error of the model as scoring for cross validation
norm_MAE = -cross_val_score(norm_linear_regression, X_norm, y_norm, cv=norm_kfold, scoring='neg_mean_absolute_error')


print( f"Normal Mean Absolute Error of k-Folds: \033[1m\033[94m{(norm_MAE)}\033[0m")
print( f"Average Normal Mean Absolute Error of k-Folds: \033[1m\033[94m{(norm_MAE.mean())}\033[0m")
print( f"Standard Deviation of Normal Mean Absolute Error of k-Folds: \033[1m\033[94m{(norm_MAE.std())}\033[0m")

Normal Mean Absolute Error of k-Folds: [1.43600110e+11 1.25615039e+11 1.53866459e+11 2.09553478e+11
 1.87980502e+11 3.25773399e+11 2.87562217e+11 1.64818123e+11
 2.32418260e+11 1.48315439e+11]
Average Normal Mean Absolute Error of k-Folds: 197950302634.87784
Standard Deviation of Normal Mean Absolute Error of k-Folds: 62834854898.340645

<h3>Mean Squared Error</h3>
Using mean squared error of the model as scoring for cross validation

In [253]:
norm_MSE = -cross_val_score(norm_linear_regression, X_norm, y_norm, cv=norm_kfold, scoring='neg_mean_squared_error')

print( f"Normal Mean Squared Error of k-Folds: \033[1m\033[94m{(norm_MSE)}\033[0m")
print( f"Average Normal Mean Squared Error of k-Folds: \033[1m\033[94m{(norm_MSE.mean())}\033[0m")
print( f"Standard Deviation of Normal Mean Squared Error of k-Folds: \033[1m\033[94m{(norm_MSE.std())}\033[0m")

Normal Mean Squared Error of k-Folds: [6.70964372e+22 7.67596306e+22 9.36826472e+22 1.46559782e+23
 1.07701077e+23 3.47848405e+23 2.32723583e+23 7.14584333e+22
 1.66699457e+23 6.17882007e+22]
Average Normal Mean Squared Error of k-Folds: 1.3723176530056451e+23
Standard Deviation of Normal Mean Squared Error of k-Folds: 8.706072930881672e+22

<h3>R-Squared</h3>
Using r-squared of the model as scoring for cross validation

In [254]:
norm_R2 = -cross_val_score(norm_linear_regression, X_norm, y_norm, cv=norm_kfold, scoring='r2')

print( f"Normal R2 of k-Folds: \033[1m\033[94m{(norm_R2)}\033[0m")
print( f"Average Normal R2 of k-Folds: \033[1m\033[94m{(norm_R2.mean())}\033[0m")
print( f"Standard Deviation of Normal R2 of k-Folds: \033[1m\033[94m{(norm_R2.std())}\033[0m")

Normal R2 of k-Folds: [2.04280174e+24 3.24424108e+24 7.16697039e+24 1.13897576e+25
 9.61437855e+24 1.69652025e+25 2.06882062e+25 5.21681321e+24
 1.24299736e+25 6.64559919e+24]
Average Normal R2 of k-Folds: 9.540394404468576e+24
Standard Deviation of Normal R2 of k-Folds: 5.654542831098282e+24

<h3>Explained Variance Score</h3>
Using explained variance score of the model as scoring for cross validation

In [255]:
norm_EV = -cross_val_score(norm_linear_regression, X_norm, y_norm, cv=norm_kfold, scoring='explained_variance')

print( f"Normal Explained Variance of k-Folds: \033[1m\033[94m{(norm_EV)}\033[0m")
print( f"Average Normal Explained Variance of k-Folds: \033[1m\033[94m{(norm_EV.mean())}\033[0m")
print( f"Standard Deviation of Normal Explained Variance of k-Folds: \033[1m\033[94m{(norm_EV.std())}\033[0m")

Normal Explained Variance of k-Folds: [2.00796936e+24 3.24122773e+24 6.46242691e+24 1.13831956e+25
 9.58929715e+24 1.67667886e+25 2.04107606e+25 5.21267788e+24
 1.24203917e+25 6.13385183e+24]
Average Normal Explained Variance of k-Folds: 9.362858725861383e+24
Standard Deviation of Normal Explained Variance of k-Folds: 5.639039018562067e+24

<h3>Root Mean Squared Error</h3>
Using root mean squared error of the model as scoring for cross validation

In [256]:
norm_RMSE = np.sqrt(norm_MSE)

print( f"Normal Root Mean Squared Error: \033[1m\033[94m{(norm_RMSE)}\033[0m")
print( f"Average Normal Root Mean Squared Error: \033[1m\033[94m{(norm_RMSE.mean())}\033[0m")
print( f"Standard Deviation of Normal Root Mean Squared Error: \033[1m\033[94m{(norm_RMSE.std())}\033[0m")

Normal Root Mean Squared Error: [2.59029800e+11 2.77055284e+11 3.06076211e+11 3.82831271e+11
 3.28178423e+11 5.89786745e+11 4.82414327e+11 2.67317102e+11
 4.08288448e+11 2.48572325e+11]
Average Normal Root Mean Squared Error: 354954993754.68555
Standard Deviation of Normal Root Mean Squared Error: 106012818607.82506

<h2>Hold-Out Validation</h2>
Use hold-out validation to evaluate the model

<h3>Mean Absolute Error</h3>
Using mean absolute error of the model as scoring for hold-out validation <i>(the best value is 0.0)</i>

In [257]:
norm_MAE_holdout = mean_absolute_error(Y_norm_test, Y_norm_pred)
color = "\033[92m" if norm_MAE_holdout < 0.5 else "\033[91m"

print( f"Normal Mean Absolute Error of Holdout: \033[1m{color}{norm_MAE_holdout}\033[0m")

Normal Mean Absolute Error of Holdout: 162286526976.644

<h3>Mean Squared Error</h3>
Using mean squared error of the model as scoring for hold-out validation <i>(the best value is 0.0)</i>

In [258]:
norm_MSE_holdout = mean_squared_error(Y_norm_test, Y_norm_pred)
color = "\033[92m" if norm_MSE_holdout < 0.5 else "\033[91m"

print( f"Normal Mean Squared Error of Holdout: \033[1m{color}{norm_MSE_holdout}\033[0m")

Normal Mean Squared Error of Holdout: 2.1314681880906375e+23

<h3>R-Squared Error</h3>
Using r-squared error of the model as scoring for hold-out validation <i>(the best value is 1.0)</i>

In [259]:
norm_R2_holdout = r2_score(Y_norm_test, Y_norm_pred)
color = "\033[92m" if norm_R2_holdout > 0.5 else "\033[91m"

print( f"Normal R2 of Holdout: \033[1m{color}{norm_R2_holdout}\033[0m")

Normal R2 of Holdout: -7.519279853384749e+24

<h3>Explained Variance Score</h3>
Using explained variance score of the model as scoring for hold-out validation  <i>(the best value is 1.0)</i>

In [260]:
norm_EV_holdout = explained_variance_score(Y_norm_test, Y_norm_pred)
color = "\033[92m" if norm_EV_holdout > 0.5 else "\033[91m"

print( f"Normal Explained Variance of Holdout: \033[1m{color}{norm_EV_holdout}\033[0m")

Normal Explained Variance of Holdout: -7.444000974712178e+24

<h3>Root Mean Squared Error</h3>
Using root mean squared error of the model as scoring for hold-out validation  <i>(the best value is 0.0)</i>

In [261]:
norm_RMSE_holdout = np.sqrt(norm_MSE_holdout)
color = "\033[92m" if norm_RMSE_holdout < 0.5 else "\033[91m"

print( f"Normal Root Mean Squared Error of Holdout: \033[1m{color}{norm_RMSE_holdout}\033[0m")

Normal Root Mean Squared Error of Holdout: 461678263305.8045

<h1>Loading and Viewing Data for Cross Validation in 10 folds</h1>
Import the database with the features selected.

In [262]:
# read the data
df_sel = pd.read_csv('Group 11_Dataset.csv')
df_sel

,Dedicated Graphic Memory Capacity,SSD Capacity,RAM,Cache,Screen Resolution,Bluetooth,Weight,Brightness,Refresh Rate,HDD Capacity,...,Warranty Summary_3 Year Carry-In Warranty,Warranty Summary_3 Year Premier Support Warranty,Brand_asus,Brand_dell,Brand_hp,Brand_infinix,Brand_lenovo,Brand_msi,Brand_redmibook,Price
0,0.50,0.50,1.000,1.000000,0.400000,0.866667,1.000000,0.500000,0.166667,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.778138
1,0.50,0.50,1.000,1.000000,0.400000,0.866667,0.793103,0.500000,0.166667,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.761581
2,0.25,0.25,0.500,0.666667,0.225000,0.866667,0.855172,0.500000,0.400000,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.344684
3,0.25,0.25,0.500,0.666667,0.225000,0.833333,0.775862,0.416667,0.333333,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.290463
4,0.00,0.25,0.500,0.333333,0.225000,0.833333,0.468966,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.259595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,0.00,0.25,0.500,0.333333,0.400000,0.850000,0.375862,0.500000,0.166667,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.711149
647,0.00,0.25,0.250,0.250000,0.225000,0.833333,0.379310,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.178781
648,0.00,0.25,0.500,0.333333,0.225000,0.833333,0.513793,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.793930
649,0.00,0.25,0.250,0.125000,0.225000,0.833333,0.455172,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.283304
650,0.00,0.00,0.125,0.041667,0.113833,0.683333,0.551724,0.416667,0.166667,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.147654

<h2>Independent and Dependent Variables.</h2>
Creates a matrix of independent variables and a matrix of dependent variables.

In [263]:

# create a matrix of dependent variables
X_sel = df_sel.drop(['Price'], axis=1).values

print("selal Independent Variable Array:")
display(pd.DataFrame(X_sel))

# create a matrix of independent variables
y_sel = df_sel['Price'].values

print("selal Dependent Variable Array:")
display(pd.DataFrame(y_sel))

selal Independent Variable Array:

,0,1,2,3,4,5,6,7,8,9,...,275,276,277,278,279,280,281,282,283,284
0,0.50,0.50,1.000,1.000000,0.400000,0.866667,1.000000,0.500000,0.166667,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.50,0.50,1.000,1.000000,0.400000,0.866667,0.793103,0.500000,0.166667,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.25,0.25,0.500,0.666667,0.225000,0.866667,0.855172,0.500000,0.400000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.25,0.25,0.500,0.666667,0.225000,0.833333,0.775862,0.416667,0.333333,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.00,0.25,0.500,0.333333,0.225000,0.833333,0.468966,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,0.00,0.25,0.500,0.333333,0.400000,0.850000,0.375862,0.500000,0.166667,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
647,0.00,0.25,0.250,0.250000,0.225000,0.833333,0.379310,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
648,0.00,0.25,0.500,0.333333,0.225000,0.833333,0.513793,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
649,0.00,0.25,0.250,0.125000,0.225000,0.833333,0.455172,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
650,0.00,0.00,0.125,0.041667,0.113833,0.683333,0.551724,0.416667,0.166667,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

selal Dependent Variable Array:

            0
0    0.778138
1    0.761581
2    0.344684
3    0.290463
4    0.259595
..        ...
646  0.711149
647  0.178781
648  0.793930
649  0.283304
650  0.147654

[651 rows x 1 columns]

<h2>Training and Testing Datasets</h2>
Split the data into training and testing datasets

In [264]:
X_sel_train, X_sel_test, Y_sel_train, Y_sel_test = train_test_split(X_sel, y_sel, test_size=0.2, random_state=0)

print("Selected Features X Train:")
display(pd.DataFrame(X_sel_train))

print("Selected Features X Test:")
display(pd.DataFrame(X_sel_test))

print("Selected Features Y Train:")
display(pd.DataFrame(Y_sel_train))

print("Selected Features Y Test:")
display(pd.DataFrame(Y_sel_test))

Selected Features X Train:

,0,1,2,3,4,5,6,7,8,9,...,275,276,277,278,279,280,281,282,283,284
0,0.00,0.125,0.250,0.250000,0.225000,0.683333,0.544828,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.25,0.125,0.500,0.666667,0.225000,0.833333,0.737931,0.416667,0.333333,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.00,0.250,0.500,0.333333,0.225000,0.833333,0.482759,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.00,0.000,0.250,0.250000,0.225000,0.683333,0.620690,0.333333,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.125,0.250,0.208333,0.225000,0.700000,0.627586,0.416667,0.166667,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,0.00,0.250,0.500,0.333333,0.225000,0.850000,0.400000,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
516,0.00,0.000,0.250,0.250000,0.225000,0.683333,0.620690,0.416667,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
517,0.00,0.250,0.500,0.333333,0.225000,0.833333,0.503448,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
518,0.00,0.250,0.250,0.250000,0.225000,0.700000,0.610345,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
519,0.00,0.000,0.125,0.166667,0.113833,0.683333,0.620690,0.333333,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

Selected Features X Test:

,0,1,2,3,4,5,6,7,8,9,...,275,276,277,278,279,280,281,282,283,284
0,0.000,0.250,0.250,0.333333,0.225000,0.850000,0.479310,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.250,0.250,0.500,1.000000,0.225000,0.850000,0.827586,0.416667,0.333333,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.000,0.250,0.500,0.333333,0.225000,0.850000,0.510345,0.500000,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.000,0.250,0.250,0.250000,0.225000,0.700000,0.610345,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.125,0.250,0.500,0.333333,0.444444,0.833333,0.465517,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,0.000,0.125,0.125,0.166667,0.225000,0.833333,0.620690,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
127,0.125,0.250,0.250,0.250000,0.225000,0.833333,0.465517,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
128,0.000,0.000,0.125,0.041667,0.113833,0.683333,0.551724,0.416667,0.166667,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
129,0.000,0.125,0.250,0.166667,0.225000,0.833333,0.620690,0.416667,0.166667,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
130,0.000,0.125,0.250,0.250000,0.225000,0.833333,0.620690,1.000000,0.166667,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

Selected Features Y Train:

            0
0    0.129110
1    0.228451
2    0.165535
3    0.148978
4    0.137389
..        ...
515  0.495530
516  0.148978
517  0.235074
518  0.168847
519  0.112553

[520 rows x 1 columns]

Selected Features Y Test:

            0
0    0.188715
1    0.390708
2    0.168847
3    0.164211
4    0.294679
..        ...
126  0.119209
127  0.182122
128  0.147654
129  0.115865
130  0.168847

[131 rows x 1 columns]

<h1>Linear Regression Model</h1>
Create a linear regression model then fit the training datasets

In [265]:
# create a linear regression model
sel_linear_regression = LinearRegression()
sel_linear_regression.fit(X_sel_train, Y_sel_train)

# predict the test set results
Y_sel_pred = sel_linear_regression.predict(X_sel_test)

<h2>K-Fold Cross Validation</h2>
Use k-fold cross validation to get the accuracy of the model

In [266]:
sel_kfold = KFold(n_splits=10, random_state=0, shuffle=True)

<h3>Mean Absolute Error</h3>
Using mean absolute error of the model as scoring for cross validation

In [267]:
# calculate the mean absolute error of the model as scoring for cross validation
sel_MAE = -cross_val_score(sel_linear_regression, X_sel, y_sel, cv=sel_kfold, scoring='neg_mean_absolute_error')


print( f"Selected Feastures Mean Absolute Error of k-Folds: \033[1m\033[94m{(sel_MAE)}\033[0m")
print( f"Average Selected Feastures Mean Absolute Error of k-Folds: \033[1m\033[94m{(sel_MAE.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures Mean Absolute Error of k-Folds: \033[1m\033[94m{(sel_MAE.std())}\033[0m")

Selected Feastures Mean Absolute Error of k-Folds: [6.39517055e+09 9.56005797e+08 1.56039437e+08 2.09067999e+09
 2.00842085e+08 4.10424901e+08 8.97992031e+08 4.61899177e+08
 4.53047734e+08 3.90558397e+08]
Average Selected Feastures Mean Absolute Error of k-Folds: 1241266009.653122
Standard Deviation of Selected Feastures Mean Absolute Error of k-Folds: 1799620689.528277

<h3>Mean Squared Error</h3>
Using mean squared error of the model as scoring for cross validation

In [268]:
sel_MSE = -cross_val_score(sel_linear_regression, X_sel, y_sel, cv=sel_kfold, scoring='neg_mean_squared_error')

print( f"Selected Feastures Mean Squared Error of k-Folds: \033[1m\033[94m{(sel_MSE)}\033[0m")
print( f"Average Selected Feastures Mean Squared Error of k-Folds: \033[1m\033[94m{(sel_MSE.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures Mean Squared Error of k-Folds: \033[1m\033[94m{(sel_MSE.std())}\033[0m")

Selected Feastures Mean Squared Error of k-Folds: [8.96850487e+20 4.00002956e+19 1.28803899e+18 6.28590262e+19
 1.95947405e+18 1.02415843e+19 1.45076418e+19 4.34797840e+18
 4.07425685e+18 5.41516159e+18]
Average Selected Feastures Mean Squared Error of k-Folds: 1.0415439444660832e+20
Standard Deviation of Selected Feastures Mean Squared Error of k-Folds: 2.6491439865536882e+20

<h3>R-Squared</h3>
Using r-squared of the model as scoring for cross validation

In [269]:
sel_R2 = -cross_val_score(sel_linear_regression, X_sel, y_sel, cv=sel_kfold, scoring='r2')

print( f"Selected Feastures R2 of k-Folds: \033[1m\033[94m{(sel_R2)}\033[0m")
print( f"Average Selected Feastures R2 of k-Folds: \033[1m\033[94m{(sel_R2.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures R2 of k-Folds: \033[1m\033[94m{(sel_R2.std())}\033[0m")

Selected Feastures R2 of k-Folds: [2.73052909e+22 1.69061004e+21 9.85383912e+19 4.88503092e+21
 1.74920490e+20 4.99500787e+20 1.28967199e+21 3.17423572e+20
 3.03797662e+20 5.82425010e+20]
Average Selected Feastures R2 of k-Folds: 3.714720973874486e+21
Standard Deviation of Selected Feastures R2 of k-Folds: 7.979939921122252e+21

<h3>Explained Variance Score</h3>
Using explained variance score of the model as scoring for cross validation

In [270]:
sel_EV = -cross_val_score(sel_linear_regression, X_sel, y_sel, cv=sel_kfold, scoring='explained_variance')

print( f"Selected Feastures Explained Variance of k-Folds: \033[1m\033[94m{(sel_EV)}\033[0m")
print( f"Average Selected Feastures Explained Variance of k-Folds: \033[1m\033[94m{(sel_EV.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures Explained Variance of k-Folds: \033[1m\033[94m{(sel_EV.std())}\033[0m")

Selected Feastures Explained Variance of k-Folds: [2.69567120e+22 1.65210888e+21 9.69195845e+19 4.86708596e+21
 1.73090506e+20 4.91871087e+20 1.21798718e+21 3.15040084e+20
 2.93256677e+20 5.79840386e+20]
Average Selected Feastures Explained Variance of k-Folds: 3.664391233287943e+21
Standard Deviation of Selected Feastures Explained Variance of k-Folds: 7.880932225857524e+21

<h3>Root Mean Squared Error</h3>
Using root mean squared error of the model as scoring for cross validation

In [271]:
sel_RMSE = np.sqrt(sel_MSE)

print( f"Selected Feastures Root Mean Squared Error: \033[1m\033[94m{(sel_RMSE)}\033[0m")
print( f"Average Selected Feastures Root Mean Squared Error: \033[1m\033[94m{(sel_RMSE.mean())}\033[0m")
print( f"Standard Deviation of Selected Feastures Root Mean Squared Error: \033[1m\033[94m{(sel_RMSE.std())}\033[0m")

Selected Feastures Root Mean Squared Error: [2.99474621e+10 6.32457869e+09 1.13491806e+09 7.92836844e+09
 1.39981215e+09 3.20024754e+09 3.80888984e+09 2.08518066e+09
 2.01847885e+09 2.32704997e+09]
Average Selected Feastures Root Mean Squared Error: 6017498631.014395
Standard Deviation of Selected Feastures Root Mean Squared Error: 8242821402.429402

<h2>Hold-Out Validation</h2>
Use hold-out validation to evaluate the model

<h3>Mean Absolute Error</h3>
Using mean absolute error of the model as scoring for hold-out validation <i>(the best value is 0.0)</i>

In [272]:
sel_MAE_holdout = mean_absolute_error(Y_sel_test, Y_sel_pred)
color = "\033[92m" if sel_MAE_holdout < 0.5 else "\033[91m"

print( f"Selected Feastures Mean Absolute Error of Holdout: \033[1m{color}{sel_MAE_holdout}\033[0m")

Selected Feastures Mean Absolute Error of Holdout: 4465264888.972297

<h3>Mean Squared Error</h3>
Using mean squared error of the model as scoring for hold-out validation <i>(the best value is 0.0)</i>

In [273]:
sel_MSE_holdout = mean_squared_error(Y_sel_test, Y_sel_pred)
color = "\033[92m" if sel_MSE_holdout < 0.5 else "\033[91m"

print( f"Selected Feastures Mean Squared Error of Holdout: \033[1m{color}{sel_MSE_holdout}\033[0m")

Selected Feastures Mean Squared Error of Holdout: 3.923648980697128e+20

<h3>R-Squared Error</h3>
Using r-squared error of the model as scoring for hold-out validation <i>(the best value is 1.0)</i>

In [274]:
sel_R2_holdout = r2_score(Y_sel_test, Y_sel_pred)
color = "\033[92m" if sel_R2_holdout > 0.5 else "\033[91m"

print( f"Selected Feastures R2 of Holdout: \033[1m{color}{sel_R2_holdout}\033[0m")

Selected Feastures R2 of Holdout: -1.384163971911691e+22

<h3>Explained Variance Score</h3>
Using explained variance score of the model as scoring for hold-out validation  <i>(the best value is 1.0)</i>

In [275]:
sel_EV_holdout = explained_variance_score(Y_sel_test, Y_sel_pred)
color = "\033[92m" if sel_EV_holdout > 0.5 else "\033[91m"

print( f"Selected Feastures Explained Variance of Holdout: \033[1m{color}{sel_EV_holdout}\033[0m")

Selected Feastures Explained Variance of Holdout: -1.3694549012421785e+22

<h3>Root Mean Squared Error</h3>
Using root mean squared error of the model as scoring for hold-out validation  <i>(the best value is 0.0)</i>

In [276]:
sel_RMSE_holdout = np.sqrt(sel_MSE_holdout)
color = "\033[92m" if sel_RMSE_holdout < 0.5 else "\033[91m"

print( f"Selected Feastures Root Mean Squared Error of Holdout: \033[1m{color}{sel_RMSE_holdout}\033[0m")

Selected Feastures Root Mean Squared Error of Holdout: 19808202797.571335

# CONCLUSION
Based on the results, the model with the **selected features** performed better than the model with all the features. <br>
The model with the **selected features** has a lower **mean absolute error**, **mean squared error**, **root mean squared error**, and higher **R2** and **explained variance**.

The **Linear Regression** model was the worst performing model ever tested using this dataset, while the **Decision Tree Regression** model was the best model for this dataset, with the **Random Forest Regression** model being the 2nd and **Support Vector Regression** model being the 3rd.